### ISSUE TITLE
Issue with file naming when saving diagram image

### ISSUE THREAD

**Issue by esteinberg** [esteinberg/plantuml4idea#101]
Steps to reproduce:
- open save diagram dialog
- place cursor on existing file
- type new name 
- Click Ok

Issue:
New name is not effective, and dialog prompts just to rewrite the selected file

![image](https://cloud.githubusercontent.com/assets/265887/7775057/9a5df5f8-0064-11e5-9480-d26e0572589b.png)

**Comment by krasa** [comment]
https://youtrack.jetbrains.com/issue/IDEA-112124
