### ISSUE TITLE
missing syntax hilighting for includes (*.iuml)

### ISSUE THREAD

**Issue by DaRolla** [esteinberg/plantuml4idea#109]
Hi there,
on their webpage the PlantUML team explains their include mechanism: http://de.plantuml.com/preprocessing.html

Using Android Studio 1.4 Preview 3 I get no syntax hilighting for my colors.iuml file which I include in my sequence diagram using: `!include colors.iuml`

I think the plugin misses to registrate the file extension *.iuml.

Cheers,
DaRolla

**Comment by krasa** [comment]
iuml extension registered, but you will have to include in that file @startuml and @enduml, otherwise plauntuml library cannot validate it
