### ISSUE TITLE
Parse PlantUML syntax from code

### ISSUE THREAD

**Issue by compunova** [esteinberg/plantuml4idea#110]
Dear plantuml4idea developers!

I have been looking for the with the code documentation solution, which would enable me to document relations between components of my code. This would enable us to create documentation whch reflects the code of the projuct thus making it possible to keep it up to date. I use PyCharm 4.5.3 Pro and the built in autogenerated UML diagrams are quite basic with minimal ability to extend them. Within the plugins repo of Jetbrains I then found your plugin, but then realized, after confirming it with Ivan, that plantuml4idea does not have capabilities to extract PlantUML syntax from code.

I beleive it should be be possible to enable code parsing, where PlatUML syntax would be kept within comments such as:

```
def function(param1):
    """
    Function desciption
    :param param1:
    :return:

    .. uml:: 
          @startuml
          ...
         @enduml
    """

    ...code goes here...
    """
    .. uml:: 
          @startuml
          ...
         @enduml
    """

```

The reason that IMHO this form is a better approach is because it could tie nicely, albeit probably with some hacking, with Spinx doc generation from docstrings (see http://goo.gl/5mN3Ar).

After PlantUML diagrams are generated from within the code, it would be helpful to then navigate to the code from within the genarated PlantUML diagram, much like the generated UML diagrams with the built in UML diagram generator.

And then the final touch is code generation from within the PlantUML diagram which would allow addition of classes and members from within the diagram, much like the built in UML diagram viewer.

It may be a tall order but it would be a great step towards tying the documentation and code and having one platform to do it from.

I'd be glad to be a tester for this functionality. I'm also available to discuss this further in any format.

Best regards,
Roman

**Comment by krasa** [comment]
What exactly is the problem? It works fine for me.
