### ISSUE TITLE
I'd like to implement auto-compile : on file change regenerate images with default settings

### ISSUE THREAD

**Issue by binarytemple** [esteinberg/plantuml4idea#111]
This is my first attempt to hack an intellij plugin. I'd like to listen for file modification events and kick off plantuml on the command line to generate the corresponding image file. 

I don't have a clue on how to get started with intellij though. I've checked out the project and compiled it but can't figure the runtime configuration. 

Are there any resources you could point me towards?

**Comment by binarytemple** [comment]
For example, I receive this error message.

![example error message](https://cloud.githubusercontent.com/assets/419046/10703324/2251d930-79c7-11e5-871b-d9878f73e2bd.png)

**Comment by binarytemple** [comment]
I've managed to get it running an make a first attempt at listening for file change events - https://github.com/binarytemple/plantuml4idea/commit/fc11ed30cf136aaaeb780a5d96ccf94fe989adf0 

Have you got any suggestions of a good next step? Docs or ideas.

**Comment by krasa** [comment]
Why do you want to use command line?

IntelliJ plugin already listens to modifications and renders the image https://github.com/esteinberg/plantuml4idea/blob/1.x/src/org/plantuml/idea/toolwindow/listener/PlantUmlDocumentListener.java
you could easily save the image to a file if you want.

If you need to listen to external modification events, then there are afaik some file watchers in IntelliJ which listens to file system... depends on the use case, which is not clear to me..

**Comment by binarytemple** [comment]
I want to add support for auto-creating the image corresponding to the uml diagram every time a project build is triggered. I could do something with Maven, grade or whatever but direct support in Intellij would make it much more cconvenient for the user. The generated images would land in the build output directory.Thanks for the pointer, I'll investigate when I get home.Bryan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Vojtěch KrásaSent: Saturday, October 24, 2015 11:10 AMTo: esteinberg/plantuml4ideaReply To: esteinberg/plantuml4ideaCc: Bryan HuntSubject: Re: [plantuml4idea] I'd like to implement auto-compile : on file change regenerate images with default settings (#111)Why do you want to use command line?

IntelliJ plugin already listens to modifications and renders the image https://github.com/esteinberg/plantuml4idea/blob/1.x/src/org/plantuml/idea/toolwindow/listener/PlantUmlDocumentListener.java
you could easily save the image to a file if you want.

If you need to listen to external modification events, then there are afaik some file watchers in IntelliJ which listens to file system... depends on the use case, which is not clear to me..

—Reply to this email directly or view it on GitHub.

**Comment by binarytemple** [comment]
hacked away a while, the resorted to stack-overflow - earned the tumbleweed badge.

**Comment by binarytemple** [comment]
Ah sorry for delay in replying - I think my original goal was that you could open a project that just contained plantuml files, run rebuild project and it would rebuild all the png files - I guess I was just trying to remove the step of having to click on each file individually, choose export image and work ones way through the file save dialog.

**Comment by krasa** [comment]
So what is the problem? You could probably make an indexer to keep track of all puml files in the project, subscribe to com.intellij.openapi.compiler.CompilerTopics#COMPILATION_STATUS and regenerate your images.

**Comment by binarytemple** [comment]
Thanks Vojetch I'll give it a try. I'm not massively familiar with intellij
API.
