### ISSUE TITLE
Performance optimization at plugin level

### ISSUE THREAD

**Issue by bondden** [esteinberg/plantuml4idea#112]
- The issue: 
Image updates immediately on code change
as a result: **slow performance** on complex diagrams.

- Possible improvement:
Add a **delay** between key up event and **rendering** run.

**Comment by krasa** [comment]
done.

**Comment by bondden** [comment]
Thanks a lot! Waiting for the release!

**Comment by krasa** [comment]
You can try it now, it will need some testing before release... https://github.com/esteinberg/plantuml4idea/releases/download/2.0.0/plantuml4idea.zip
