### ISSUE TITLE
Please provide support for Activity2 diagrams

### ISSUE THREAD

**Issue by hznut** [esteinberg/plantuml4idea#113]
The [Activity2](http://plantuml.com/activity2.html) diagrams provide lot of enhanced capabilities like repeat loops etc. which are really useful. It'll be good to have support for them.

**Comment by krasa** [comment]
What support do you have in mind? It should work in the current version.

**Comment by hznut** [comment]
'repeat loop' and 'while' keyword support for instance. Currently when I
use them the plugin does not recognize them and throws error.

**Comment by krasa** [comment]
I will update the library

**Comment by hznut** [comment]
Thanks. Appreciate it.

**Comment by krasa** [comment]
Install this: https://github.com/esteinberg/plantuml4idea/releases/download/1.9.0-SNAPSHOT/plantuml4idea.zip

**Comment by hznut** [comment]
Installed the 1.9.0-SNAPSHOT and able to work with the new syntax as well as old syntax. Thanks!

When can we expect a release version available in IntelliJ plugin repository ?

**Comment by krasa** [comment]
I could release it anytime, but I want to implement some features first and test if everything works.

**Comment by hznut** [comment]
Sounds good. Thanks! Looking forward to the release. The issue is resolved for me for now.
