### ISSUE TITLE
activity(beta): text to arrows not visible in JetBrains plugin

### ISSUE THREAD

**Issue by axd1967** [esteinberg/plantuml4idea#116]
for
```
@startuml
start
:hello;
fork
-> t1;
:xxx;
fork again
-> t2;
:yyy;
end fork
stop
@enduml

```
from [website](http://www.planttext.com/planttext): 
![plug](http://www.plantuml.com/plantuml/img/SoWkIImgAStDuU82ixYuh39IStBohRcuqlABihbqxHHA3Asvh2egAg122edfYPbvN60P8w2OLMLb9P1ApKjH0Ei0cfDVmCNb01G06Gi0)

using PlantUML plugin (1.8.1):

![puml](https://cloud.githubusercontent.com/assets/3529789/12873677/fb60ea22-cdc3-11e5-8560-0ab70e2c0eeb.png)

**Comment by krasa** [comment]
Fixed.
