### ISSUE TITLE
network dependency?

### ISSUE THREAD

**Issue by axd1967** [esteinberg/plantuml4idea#117]
it looks like the plugin connects to the Internet for each diagram generation... (at least, that's what I conclude from the perceived slow update, and the systematic network access peak in Windows Task Manager).

can the plugin be used without network connection? why does it need a connection?

**Comment by krasa** [comment]
It should not do any networking, unless Graphviz does something strange... You could easily check which processes use your network in the Resource Monitor.

**Comment by axd1967** [comment]
close as non-issue: the network was part of the issue because of a link in a document that links to the plantuml proxy server.
