### ISSUE TITLE
Support generate platuml link

### ISSUE THREAD

**Issue by wenerme** [esteinberg/plantuml4idea#119]
Use platuml's server(http://plantuml.com/plantuml/uml/IybCBqeio51mLwZcIbJGjLD8uge50000) is very convenient.I always edit plantuml in idea, and copy paste to plantuml's server to generate the link, then change the png to svg, then use this link in markdown.

plantuml4idea can generate the svg ,png or form link will be very useful.

**Comment by krasa** [comment]
pull request welcomed

**Comment by krasa** [comment]
http://plantuml.sourceforge.net/qa/?qa=4614/plantuml-server-integration-with-ide
