### ISSUE TITLE
Page title in dropdown

### ISSUE THREAD

**Issue by pouledodue** [esteinberg/plantuml4idea#122]
join the title's of pages (when there is one) with the page number into the dropdown.

**Comment by pouledodue** [comment]
if possible

**Comment by krasa** [comment]
It would be probably possible, but hard, not sure if it's worth it.

**Comment by pouledodue** [comment]
ok i can live without it.

**Comment by krasa** [comment]
I found some APIs to get the title, so it should not be that hard.

**Comment by pouledodue** [comment]
small bug:
say I have a .puml doc with 7 pages.
If I replace the entire content of the doc with the content of another .puml document (by copy-paste),
the menu keeps dispaying the old content titles

**Comment by pouledodue** [comment]
is it possible the bug is related to the line `idea.partialRender` ?
Seems to work better when I remove the line.
I need it though

**Comment by krasa** [comment]
Yes, with 'idea.partialRender, only the selected page is parsed+rendered, so other pages might not have initialized title, or wrong one. I could parse all pages, but it would be a performance hit.

Without it, everything is always parsed, so it have right titles.

**Comment by krasa** [comment]
You know what, I will try to fix it, to see how much slower it would get.

**Comment by pouledodue** [comment]
works great!! many thanks, helps me a lot

**Comment by krasa** [comment]
No problem. It's better this way, although it was pretty hard to do it right, after all. :)
