### ISSUE TITLE
touch scrolling doesn't work in PyCharm 2016.2 EAP

### ISSUE THREAD

**Issue by mark-anders** [esteinberg/plantuml4idea#124]
What I'm calling "touch scrolling", where you don't click and drag but just use 2 fingers on the touchpad or lightly touch the mouse, does not work when used in PyCharm 2016.2 EAP, and possibly other .2 releases.  It DOES work in in PyCharm 2016.1, so something much have changed.

Currently, the only way to scroll is to actually click and drag, which is, pun intended, a drag. :-)

**Comment by krasa** [comment]
Fixed.

**Comment by mark-anders** [comment]
Thank you! I love the plug-in.

Mark
