### ISSUE TITLE
Setting "Graphviz dot executable" is ignored

### ISSUE THREAD

**Issue by chaudum** [esteinberg/plantuml4idea#127]
Hi,
I'm using version 2.2.1 with IntelliJ 2016.1.3 on OSX.
PlantUML cannot find the `dot` executable although I've set the path in the settings to `/opt/local/bin/dot`. Seems that it still tries to use `/usr/bin/dot`.

<img width="913" alt="screen shot 2016-06-29 at 10 58 43" src="https://cloud.githubusercontent.com/assets/281260/16446691/22b36826-3de9-11e6-9c0c-5b1219e3a667.png">

```console
> which dot
/opt/local/bin/dot
```

**Comment by chaudum** [comment]
In `1.9.0` the custom path is still taken into account.

**Comment by arnaudroques** [comment]
As workaround, you can try to set up GRAPHVIZ_DOT environment variable to /opt/local/bin/dot
See http://plantuml.com/graphvizdot.html

**Comment by krasa** [comment]
Probably plantuml OS specific issue, it works just fine for me on WIndows.
