### ISSUE TITLE
"Copy to ASCII" throwing Exceptions

### ISSUE THREAD

**Issue by pdelre** [esteinberg/plantuml4idea#129]
When trying to generate ASCII versions, Exceptions are thrown to the Event Log. Additionally, there's a typo where "ASII" should be "ASCII".

When selecting **Copy diagram(s) to clipboard as ASII**, it logs `RenderingCancelledException: java.lang.UnsupportedOperationException: ATXT`.

When selecting **Copy diagram(s) to clipboard as Unicode ASII**, it logs `RenderingCancelledException: java.lang.UnsupportedOperationException: UTXT`.

```
IntelliJ IDEA 2016.1.3
Build #IU-145.1617, built on June 3, 2016
JRE: 1.8.0_76-release-b198 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by krasa** [comment]
Plantuml does not support ASCII for all diagram types, nothing I can do about that.
But I fixed the typo and a different exception. Thanks.

**Comment by pdelre** [comment]
Fair enough. In that case it's more of a UX issue. Maybe the options should only appear if the diagram is supported. Or show a better message than the Exception in the Event Log.

**Comment by krasa** [comment]
Better message would be doable, pull request welcomed. :)
