### ISSUE TITLE
Default Shortcuts conflict with default system shortcuts 

### ISSUE THREAD

**Issue by dedeibel** [esteinberg/plantuml4idea#131]
Thanks for the great plugin - works nicely to generate the diagrams. 

But there are shortcuts that conflict with default system shortcuts on my system, which is a little bit annoying and might be prevented. 

Debian Linux on KDE but should be the same on most common WMs and also Windows.

I would expect Alt+F to open the File Menu Dropdown, this is quite Standard in most apps. But the plugin does bind them now.

I removed the shortcut manual so far but I think it might be a problem for others too.

**Comment by krasa** [comment]
Perhaps ctrl+alt+shit+F and G (for reload) would be better.
