### ISSUE TITLE
Please upgrade to PlantUML v8048/8049

### ISSUE THREAD

**Issue by noamtamim** [esteinberg/plantuml4idea#134]
8048 does not require Graphviz, which means plugin installation is simpler. It also solves some bugs.

Is it possible to enter path to plantuml.jar?

**Comment by noamtamim** [comment]
As a temporary workaround, I removed plantuml.8043.jar from the plugin's lib directory (on my Mac $HOME/Library/Application Support/IdeaIC2016.2/plantuml4idea/lib) and replaced it with the latest version.

**Comment by rkorrelboom** [comment]
Another option would be to be able to specify a custom location of the plantuml.jar in the plugin settings window

**Comment by krasa** [comment]
Graphviz is still required. Why do you think it isn't?
