### ISSUE TITLE
error installing on intellij 2016.3

### ISSUE THREAD

**Issue by marcelloh** [esteinberg/plantuml4idea#137]
When trying to install the plugin from disk, intellij gives me an error after the installation, and disables the plugin again, due to the coccured error.

When trying to install from the intellij repository, I get an error as well (502), but I don;t know if that is because of me using a 2016.3 release and they block the download if the pluging for that release.

**Comment by krasa** [comment]
try it now

**Comment by marcelloh** [comment]
Works :-) Thanks
