### ISSUE TITLE
How do I use the plugin?

### ISSUE THREAD

**Issue by idvorkin** [esteinberg/plantuml4idea#138]
* I'm new to plantuml and IntelliJ so please respond like I'm a total n00b :) *

I've installed the plugin and graphviz (via homebrew)  - however I can't figure out how to use the extension? I've tried adding some plantuml in a comment but nothing happens. 

```
public class Controller {
    /*
    @startuml
        Bob->Alice : hello
    @enduml
    */
}
```

The readme mentioned you can check install correctness using the about box, how do I get to the about box.

**Comment by esteinberg** [comment]
You need to create separate *.puml file. Just use File>New and in the dropdown you should see various types of UML diagrams available. 

Once you create a file, you will see an example and rendering window called plantUML

**Comment by krasa** [comment]
It actually works anywhere, but you must click inside on the plantuml code.

**Comment by idvorkin** [comment]
Ahh, I missed the plantuml clicker on side tab. 

![image](https://cloud.githubusercontent.com/assets/280981/21531313/c7b5516c-ccfb-11e6-8305-bf993b10e9a8.png)
