### ISSUE TITLE
markdown integration

### ISSUE THREAD

**Issue by roipoussiere** [esteinberg/plantuml4idea#141]
It usually insert my UML diagrams in markdown files.

Any plan for a PlantUML integration in markdown files, using the current Markdown plugin?

Syntax suggestion:

````
```@startuml
PlantUML code here...
@enduml
```
````

which should display something like this:

![](http://i.imgur.com/yaALnUU.png)

The good point for this syntax is that it is compatible with other markdown editors (which should just display plantUML code in a code block).

**Comment by krasa** [comment]
No. Markdown plugin must integrate it itself. It has nothing to do with this one.

**Comment by krasa** [comment]
https://youtrack.jetbrains.com/issue/RUBY-19041
