### ISSUE TITLE
Formulas. ASCII Math

### ISSUE THREAD

**Issue by sledgeh** [esteinberg/plantuml4idea#142]
I tried:
```
@startuml
Bob -> Alice : Can you solve: <math>ax^2+bx+c=0</math>
Alice --> Bob: <math>x = (-b+-sqrt(b^2-4ac))/(2a)</math>
@enduml
```
but this won't render formulas.
Official documentation is on <http://plantuml.com/ascii-math>

Why this doesn't work? Old library? How to check included in plugin version?   
May be setting **"Use system library `plantuml.jar`: </path/> or <search in $PATH>"** will help.   
Thank you for attention.

**Comment by krasa** [comment]
The last line of http://plantuml.com/ascii-math :
> Since JLatexMath is bigger, you have to download it separately, then unzip the 4 jar files (batik-all-1.7.jarjlatexmath-minimal-1.0.3.jarjlm_cyrillic.jar and jlm_greek.jar) in the same folder as PlantUML.jar.

extract it to `.IntelliJIdeaXXX\config\plugins\plantuml4idea\lib`

**Comment by sledgeh** [comment]
@krasa, did not help.

What about 
> `ASCIIMathTeXImg.js` is small enough to be integrated into `PlantUML` standard distribution. 
?

**Comment by krasa** [comment]
Did you restart IntelliJ?
![image](https://cloud.githubusercontent.com/assets/1160875/24513777/65359532-1572-11e7-8b34-edcc47dbda48.png)

That JS is probably used only for those `Standalone diagrams` - which is not supported in this plugin yet, but it needs those libs too, except batik.jar.

**Comment by sledgeh** [comment]
On windows extract [plantuml-jlatexmath.zip](https://www.dropbox.com/s/z7yah4mpi2mk1mj/plantuml-jlatexmath.zip?dl=0) to `%userprofile%\.IntelliJIdeaXXX\config\plugins\plantuml4idea\lib`, where `.IntelliJIdeaXXX` could be `.CLionXXXX.X` or PHPStorm or ...

Note: I recommend copy files when IDEa is closed.
