### ISSUE TITLE
annoyance: remember preview offset while editing file

### ISSUE THREAD

**Issue by axd1967** [esteinberg/plantuml4idea#145]
when I edit a large `.puml` file in PyCharm, I want PyCharm to remember my offset selection in the preview so that I don't have to scroll the preview pane every time.

this is especially needed when I use `newpage` elements.

note that this only happens when adding new lines, not when reorganising existing lines

**Comment by krasa** [comment]
preview scroll position is remembered... you want to update it when adding new lines?

**Comment by axd1967** [comment]
well, it is an extreme PITA, don't you think? 

when you are busy adding lines, you want to see the result, but as those lines are somewhere at the bottom, the result cannot be seen until one scrolls down...

**Comment by krasa** [comment]
Pull request welcomed. Preferably with a configuration for disabling it.

**Comment by axd1967** [comment]
so you don't think it's a good idea?

**Comment by krasa** [comment]
It is a good idea, maybe too good... Configuration is really the easiest thing in this, so better safe than sorry.

**Comment by krasa** [comment]
I think it is solved by #196
