### ISSUE TITLE
Size on HiDPI Screens!

### ISSUE THREAD

**Issue by aadrian** [esteinberg/plantuml4idea#147]
The 1:1 zoom (default) display is not correct on HiDPI screens.
The same it's true for the Help content.

IMHO the plug-in should make use of the HiDPI hints it like the rest of the IDE and scale accordingly.

Thank you.

**Comment by krasa** [comment]
Pull request welcomed.

**Comment by mattbishop** [comment]
The behavior seems to be fine on my HiDPI screen. I have two--built-in macbook pro display, and external LG monitor. The images scale as expected and are high-resolution.

**Comment by aadrian** [comment]
@mattbishop as you can see, this issue was raised in 2017.  At that time the rendering was looking ugly on all 3 major OSes. Now the only one that still has rendering issues is Linux.

**Comment by krasa** [comment]
Should be solved by #213
