### ISSUE TITLE
exporting images as ascii or utf-* text does not represent the picture

### ISSUE THREAD

**Issue by Bagorolin** [esteinberg/plantuml4idea#150]
I wanted to test the feature to export pictures as text files (following called: acscii picture) and it was toatally different.
For example in a class diagram, when you turn off the attribute and method boxes they are still included in the ascii picture. Also arrows are drawn between two totaly different nodes. Not to mention that diagonal arrows aren't supported.
Can you bugfix and enhance this feature?

**Comment by krasa** [comment]
http://www.plantuml.com/plantuml/uml/ -> View as ASCII Art

is it the same as in IntelliJ?

**Comment by Bagorolin** [comment]
please check those basic examples:
[activity](http://www.plantuml.com/plantuml/uml/ROun3i8m40JxUyNgAa3A5r0Q2fw044MmBuf5V4Q-SoH-Jn9HqgrcfvZUVAZUyao7qn7ekZCuJ19UIFfkpdGTmVj4CYnIdyM4uPCeRVBz9lO0UwkAeZyX-OVtbsjJX9Bpe959PfC_-A8nZHjV2wWNZMlD5m00)
[usecase](http://www.plantuml.com/plantuml/uml/NL0nRiCm3DprYaEcUAY7Z1w2v079qcJhmjXih4Ac35CfylnGaf421GJnU3mUHHqqqP8UKt3TYRpWE4nUEf1MvBPNPQIHGVCSV4_9HsboEHSQv-nUyB77zZFxD6kUYLelBaRyCILKoONLMfp4n5ZyVKo8ttKkEbn6hx130dxID0Tk_qkhun65xKr8GQExCQ90-PSN2WXUM1tBK5IhmwQO5sYnZoBS9nw-9CLtOxpz6Adj9czxthbrGxHjpiwx3Ee33kPkF_W2)
[classdiagram](http://www.plantuml.com/plantuml/uml/PP3B2i8m44NtynLPwg9_uC9Y1GMrODk5Y8jf726If91C5xx-tRQsjC7bdNFc3idICpgkZGR0qhD3oK9gz5x4VTmfpoCRfgjAQvAiAWlAChaRIXATEiQ90oqIYtSKXRsZ4iBfQkZyZlnx7Gkwfw5lTmuV7OF-ZSD0l20jxqtJ-I98ao7B2JA2Lq-QpU43GBOs8bU62gjQFObF6MpIufZ1VdieydNMMakor-Oplm00)

**Comment by krasa** [comment]
Ok, so it is the same. Then I can't do anything. Report a bug on PlantUml itself.
