### ISSUE TITLE
The setting of the path to "dotExecutable" is not saved separately for each platform.

### ISSUE THREAD

**Issue by tshimomura** [esteinberg/plantuml4idea#156]
I use the IntelliJ with plantuml plugin on Windows and Linux.
And, I synchronize the settings of IntelliJ using "Settings repository" function.

Unfortunately, synchronizing settings registered from Linux to Windows, overwrite the path to "dotExecutable".

I want "plantuml.cfg" saved for each platform.

**Comment by tshimomura** [comment]
And, if "GRAPHVIZ_DOT" environment variable is set, I want it to be used preferentially.
see: http://plantuml.com/graphviz-dot

**Comment by krasa** [comment]
The second request done.

**Comment by krasa** [comment]
And regarding the first one. I don't think that it is necessary, just use a system variable.
