### ISSUE TITLE
Group rendering not correct

### ISSUE THREAD

**Issue by johns-codings** [esteinberg/plantuml4idea#160]
When using groups in the sequence diagram, the rendering of the group is done with a white background color for the whole group. This makes the diagram less readable.
When I have the same plant-uml diagram be rendered by the Atom plugin plantuml-viewer (https://github.com/markushedvall/plantuml-viewer), I get a better (cleaner) result.

I've added 2 different renderings of the same diagram to show the issue.

Example diagram:
@startuml

title Example on group display

skinparam BoxPadding 20
actor "User" as user
box "User device" #f6f7d8
  participant "OS" as os #ffffff
  participant "Some App" as sap #9393c4
  participant "Some other App" as oap #ff8800
end box

box "Other systems" #f6f7d8
  participant "Other Server" as ots #ff8800
end box

box "Some Environment" #dfedf8
  participant "Some Server" as sos #9393c4
end box

group Grouped sequence
  user -> sap:Perform action
  activate os
  activate user
  activate sap #9393c4
  sap -> sos:Make call
  activate sos #9393c4
  sos -> ots:GET <domain>/some-action
  activate ots #ff8800
  ots -> ots:Perform action
  ots --> sos:ok
  deactivate ots
  sos --> sap:ok
  deactivate sos
  sap --> user:Display result
  deactivate sap
end group

group App-to-App
  user -> sap:Switch
  activate sap #9393c4
  sap -> os:Switch
  os -> oap:activate
  activate oap #ff8800
  oap -> ots:Make call
  activate ots #ff8800
  ots --> oap:ok
  deactivate ots
  oap --> user:Display result
  deactivate oap
end group

deactivate os
deactivate user

@enduml
![example-group-display-atom-plantuml-viewer](https://cloud.githubusercontent.com/assets/28701480/26051387/51f794ac-3962-11e7-8adf-3a83474a794f.png)
![example-group-display-intellij](https://cloud.githubusercontent.com/assets/28701480/26051388/5209e562-3962-11e7-9aca-d3711acedd4e.png)

**Comment by krasa** [comment]
Perhaps Atom uses some old version?

 http://www.plantuml.com/plantuml/uml/ZLF1Rjim3BthAuZq73HOXotDeUY61JqDBP3s0rIBReNOeYRAMVhtfMIbbPjqc0yMPJwIxptGwfgZ3d7eEwMYZHt2UgzxBoSvU0eqU32MVQTVbEAjTLu7tSDFsjzfOwnxWYyBfPj80MOFZ646cc6GG3tIVlm41dUsmHcSjT_QxsQff4MqZVNQHPZTRd89iQJpCqrlg4VuuNq6iVPmTdbnUT5yFO6Y-2p33bXAsBPTBXSBXSw0q54ZfzkCunUEsFDdh39cWs5N957aJzhbsMktiu5SZovAHzEYQPSdA5ODEIakMjuQZdxVf3SQOFmpe6jG9JzXVfNqh-umj1Hw4CyjkMIztUaewlazplw_tMhNKfmQ4Qz-wor2exkkGbQSKYn8qRswMT_3EGl_-T7GofKKbu8F77EcJAMjCbZNZuEAk6bMCYDXoIP9gr_Z8a907heuWMgVNSm67doKLPX7ciinSN3pryRc-P_-2D62AYv8sG5VgQzMZ4fXF6diaK-bvx4Rz7zwQQgtpd1zovkWhWKgF_Wh

**Comment by krasa** [comment]
Nothing I can do.
