### ISSUE TITLE
How to control class diagram line width

### ISSUE THREAD

**Issue by peng051410** [esteinberg/plantuml4idea#167]
@startuml

abstract class Subject
class ConcreteSubject

interface Observer
class ConcreteObserver

Subject <|-- ConcreteSubject
Observer <.. ConcreteObserver

Subject "持有" -left-* Observer
ConcreteObserver -right-o "subject" ConcreteSubject

@enduml

The result:

![image](https://user-images.githubusercontent.com/5512326/29920027-3071fad6-8e7e-11e7-94c6-2cacc8ec6684.png)

**Comment by krasa** [comment]
PlantUML problem -> http://plantuml.sourceforge.net/qa/
