### ISSUE TITLE
Install instructions fail

### ISSUE THREAD

**Issue by michaelrempel** [esteinberg/plantuml4idea#168]
The animated GIF flys by on my machine. Can you publish this as a proper video that I can at least stop to see what is going on.

Also the IDE has changed, so the current one is out of date.

**Comment by krasa** [comment]
[gif](https://user-images.githubusercontent.com/1160875/55478653-7dbb2300-561c-11e9-8a58-66f5a66b5dc1.gif)

[mp4](https://mega.nz/#!66oTUIgA!ckkAdLZNHtXjIwyoSlN6BwA-vEWh_034vTRqtWZr9AM)
