### ISSUE TITLE
Request for plantuml version upgrade to 1.2017.19

### ISSUE THREAD

**Issue by nikhilw** [esteinberg/plantuml4idea#170]
One of the features (at least) I have been looking forward to for some time has been 'Collections'. It is introduced in this version. Would it be possible to support this version in the plugin?

**Comment by mgrolinger** [comment]
Hi,

there is a new request for the new 1.2018.1 version. In the meantime, you may just switch the plantuml jar to the new version in your Intellij plugins folder. That works for me.

BR,
Michael
