### ISSUE TITLE
Use the filename from "@startuml name" when exporting multiple diagrams

### ISSUE THREAD

**Issue by noamtamim** [esteinberg/plantuml4idea#174]
When I create diagrams using plantuml.jar directly,
`$ plantuml file.puml`

And the diagrams in the file define the diagram name:
`@startuml myFirstDiagram`
The exported files use this name instead of file-001 etc.

The plugin does not do it, even though it uses the same version of PlantUML (1.2018.01).

**Comment by noamtamim** [comment]
@krasa thank you for implementing this!

**Comment by paulvi** [comment]
It would be nice to mention this feature in README or wiki
