### ISSUE TITLE
Class relation and cardinality labels not visible

### ISSUE THREAD

**Issue by Varadski** [esteinberg/plantuml4idea#175]
The labels and cardinality visible on [this](goo.gl/nWE3B9) diagram are not visible in Intellij for me, but they are visible when I post the code your website (as clearly visible in the linked diagram). Any ideas why this is not working? I have graphviz-2.38.0 installed (the latest stable version) and [here's](i.imgur.com/6T3xX68.png) the PlantUml version information.

Here's what the actual diagram I'm interested in looks like: https://i.imgur.com/GxmxuOj.png
Relevant code:

user -{ test : reviewer
user -{ test : applicant
testQuestion "many" }-- "1" question
question "1" --{ "many" answer
testQuestionAnswer "many" }-- "1" answer
testQuestion "1" --{ "many" testQuestionAnswer

You'll notice the labels and the cardinality is not displaying. I've posted about this on the plantuml forums and it was suggested it might be Intellij that is changing the color settings but I'm not seeing any PlantUml specific options under "Color Scheme" so I'm assuming it is using the default settings.

**Comment by Varadski** [comment]
![buildingmanagementdiagram](https://user-images.githubusercontent.com/36164099/38037311-e4053774-32a8-11e8-827c-b81b29398ceb.png)

I assume this is a related issue, hence why I'm posting it here. The diagram does display [on the website](http://www.plantuml.com/plantuml/png/RLB1Rjim3BthAxZqu0HmcdjW6Cs25HZGeiFQUw78h2D4bZn9JXiK_VTHicndMNA8IRv7FlhHTyvpwxj6iMyLlacDyC9t2kUQDvXNwCG2XEBEGIW0Tp0BnHaK1SnVyflx-mtz5b2MB8DtXCuXx8oguCrOQArik3t10K-4rXPHWp2Aa81sMlxfa02kAqegj4uOYn7Jnh_gJarBfL6lD6h-iO1YLtuKgrqvu6bOXAB2Ege5Kan7uZWvKhj0wCBgnk_HWkUr0txaKWKFrbGlP5ci9358ael3UllqyFIx7ARcy4vjc5vAKcyAerdqtFj6fP8mLNZPURHikrrGx13NHF7jUhLg5TVX3BV2DAleEBhRq7xpIAQmlQmG6lHxKxa-SPwKZJ-rc0fl4XM1xY1roorlG4cDX8T5g8_qha2jKQUG_8CwVr91m4eHlum9QSa3NkDp95WKdkjQ8QDkr5vwIRkm_ljfk2QYpRF7FiWM0xBhfAgahlFiUuecZ9ECRsXMdcs6S48zQXwW5thszRGFpBP67z4wxgNHiAdf-ZNtE8FFr2hEy3mxPzEOj34wHxDeupuWuEjCuHdjKGg4NzOSoMvxJSNrd86IPvTDerXY3enBiP_ETNXDGH90NH4VX-57YzfH-KSC9Y2ScEoY_x6aZ4WcFAHesibptpbQAJxxZJAmg2BDxMLBrqrtXUKd38TaGn2AumNP6C4I-ijDpKGylmZhyV_hvqb4qv5OyW--bakuS9rTv94pxXeDl5PQGhAHzJvG8GACJ2GqPObCwM0akqDTTOtw2m00) but it fails locally.

If relevant, GraphViz was installed as noted [here](https://pastebin.com/LW7eRYNb).

**Comment by krasa** [comment]
Cannot reproduce, if you do not post the whole code. 
Check if the command line behaves the same as IntelliJ.
