### ISSUE TITLE
Update diagram with cursor position

### ISSUE THREAD

**Issue by chrismelikian** [esteinberg/plantuml4idea#176]
Not a bug but a feature request...

In tricky diagrams, sometimes it's not easy to know where you are in the file. It would be nice to have a 'Track cursor' feature that would update the diagram and highlight the part of the diagram where your cursor currently is. This feature could get annoying so some sort of checkbox to enable/disable would probably be needed. 

Either that or have the crosshairs style button (like IntelliJ provides in the Project View) which when clicked gives a one-off location of the item in the diagram where the cursor currently is.

**Comment by krasa** [comment]
Not feasible imho.

**Comment by krasa** [comment]
#196 should be enough, unless someone has an idea how to implement this.
