### ISSUE TITLE
Troubles with Scaling layout

### ISSUE THREAD

**Issue by KirillAmurskiy** [esteinberg/plantuml4idea#182]
If I scale my desktop layout (150% for example). Plagin draws bad. 
See artefacts in screenshots.
Windows 10 Pro. Rider 2018.1.

<img width="599" alt="screenshot_4" src="https://user-images.githubusercontent.com/5471833/40361217-3e02a40c-5dd1-11e8-867b-15764c1b5b22.png">
<img width="797" alt="screenshot_1" src="https://user-images.githubusercontent.com/5471833/40360996-8ca3acc4-5dd0-11e8-93b6-bf600e3020a5.png">
<img width="741" alt="screenshot_2" src="https://user-images.githubusercontent.com/5471833/40360997-8cc8504c-5dd0-11e8-9b13-3fd3f211d4f3.png">
<img width="745" alt="screenshot_3" src="https://user-images.githubusercontent.com/5471833/40360998-8ce92754-5dd0-11e8-98d3-ae3eb84c33fb.png">

**Comment by krasa** [comment]
Should be solved by #213
