### ISSUE TITLE
Component Diagrams not working 

### ISSUE THREAD

**Issue by kannanekanath** [esteinberg/plantuml4idea#184]
I am using the 2.10.1 version of the Plugin and the following simple three line component diagram does not render properly.

```
@startuml
component "SubmittedTicketProcessor"
@enduml
```

Other type of diagrams appear to be working okay. For example 
```

@startuml
control SubmittedTicketPoller
@enduml
```

So I know that the plugin is in fact setup properly. Is it because the plugin has to be upgraded to the latest version of PlantUML?

**Comment by AlexBaitov** [comment]
I have downloaded the latest version of Plantuml from the official site http://plantuml.com/download (it is plantuml.1.2018.8.jar).
Put it nearby plantuml.1.2018.1.jar in ~/.IntelliJIdea2018.2/config/plugins/plantuml4idea/lib.
Restarted Idea
And it failed to render almost the same way, but version of plantuml was 1.2018.1 and became 1.2018.8
![plantuml_1 2018 8_fail](https://user-images.githubusercontent.com/4568053/42449863-752d8fb8-83ac-11e8-901c-11a770d34707.png)

**Comment by krasa** [comment]
does it work from the command line?
