### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by lours1** [esteinberg/plantuml4idea#194]
Hello,
i'm using your plugin with the latest version of intelllij and ubuntu 18.04
And the click on the zoom button have no effect (no zoom in or zoom out), but the image is regenerate.

Thank you for your help

Cédric

**Comment by krasa** [comment]
Can anyone with Ubuntu provide a fix?

**Comment by krasa** [comment]
Oh, it does not zoom only for State diagram. That changes things.

**Comment by krasa** [comment]
Nope, I just had an example with a manually defined scale. Isn't that your issue too?  @lours1

**Comment by lours1** [comment]
hello
yes,
if i disable the defined scale; it's work.

Than you for yout test
