### ISSUE TITLE
MD File support

### ISSUE THREAD

**Issue by ancasicolica** [esteinberg/plantuml4idea#195]
I would appreciate it if the PlantUML rendering would also support MD-Files (the PlantUML part of course only) as used in GitLab: https://docs.gitlab.com/ee/administration/integration/plantuml.html#creating-diagrams

**Comment by krasa** [comment]
Doesn't Markdown plugin already do that?

**Comment by paulvi** [comment]
no

**Comment by krasa** [comment]
And it has to be
```
```plantuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
_```
```
not 
```
```plantuml
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
_```
````
?

**Comment by ancasicolica** [comment]
Tried it, it works both ways

![image](https://user-images.githubusercontent.com/7976812/55286131-e5ad0780-5397-11e9-9510-b7d6ae7197dc.png)

**Comment by krasa** [comment]
Problem solved :)

**Comment by paulvi** [comment]
Every diagram must be with `@startuml` and `@enduml` 



    Sequence diagram
    
    ```plantuml
    @startuml
    Alice -> Bob: Authentication Request
    Bob --> Alice: Authentication Response
    
    Alice -> Bob: Another authentication Request
    Alice <-- Bob: Another authentication Response
    @enduml
    ```
    
    Component diagram within @startuml/@enduml
    
    ```plantuml
    @startuml
    package "FaceServer" {
    
        component SecondDb
    
    }
    @enduml
    ```
    
    Component diagram
    
    ```plantuml
    @startuml
    package "FaceServer" {
    
        component MainModule
    
    }
    @enduml
    ```

**Comment by krasa** [comment]
first lines of the instructions:
- Open file, put the cursor inside of PlantUML code to render it
- PlantUML code must be inside @startuml and @enduml tags to be rendered
:)
