### ISSUE TITLE
Plugin does not work together with RST-files

### ISSUE THREAD

**Issue by jo-as** [esteinberg/plantuml4idea#199]
When using plantuml-snippets inside RST-files (ReStructuredText), the plugin does not render it..
It might be linked to the fact, hat PyCharm itself is parsing RST-files, but is not able to interprete the uml-keywords..

**Comment by krasa** [comment]
example of such file?

**Comment by pJunger** [comment]
I think any file will do, e.g. a 'test.rst' with such a content:
`Test
=======

@startuml
UI -> Mod : update()
Mod --> UI
@enduml
`
