### ISSUE TITLE
add more preprocessor support

### ISSUE THREAD

**Issue by remcoboerma** [esteinberg/plantuml4idea#201]
Hi, 
It would be great for my case to have some heavy pre-processing on the plantuml code before it's handed over the plantuml "binary". 
A change so rendering is done on a webserver would be great as well, i'll add the pre-processing on the webserver but have the plugin display the digram with the same smoothness as it has now. 

I'm not a java programmer so i can't help you there.

**Comment by krasa** [comment]
Still need it? And what kind of preprocessing are you doing?
