### ISSUE TITLE
@startgantt

### ISSUE THREAD

**Issue by mhailstone** [esteinberg/plantuml4idea#202]
Is `@startgantt` supported? If not, do you have plans to support it in the future?
http://plantuml.com/gantt-diagram

**Comment by aadrian** [comment]
https://github.com/esteinberg/plantuml4idea/blob/9f65501c3035e31ebb454370e38283b71ee027ad/src/org/plantuml/idea/plantuml/PlantUml.java#L53  seems to restrict the type of diagrams supported - these values does not seem to be red from plantuml itself, but hardocded :( .
