### ISSUE TITLE
Generation of PlantUML input for a sequence diagram describing a Python script?

### ISSUE THREAD

**Issue by monocongo** [esteinberg/plantuml4idea#203]
Can this plugin generate PlantUML input from Python code? For example is there a way to run my Python code and have it generate a PlantUML input file that produces a sequence diagram when rendered by PlantUML? I have Python code that contains numerous steps and I'd like to automate the creation of an input file for PlantUML in order to generate a sequence diagram that describes the multiple steps taken by the code as it executes. Basically, I'm trying to avoid writing the sequence diagram by hand and hoping that this (or another?) tool can do that for me.

Thanks in advance for any suggestions.

**Comment by krasa** [comment]
It cannot generate any PlantUML code and will not without a pull request.
