### ISSUE TITLE
Setting for PLANTUML_LIMIT_SIZE

### ISSUE THREAD

**Issue by Sigurs** [esteinberg/plantuml4idea#204]
Settings page needs an option to set the PLANTUML_LIMIT_SIZE variable to be able to create large diagrams.

To quote PlantUML FAQ ( [http://plantuml.com/faq](http://plantuml.com/faq) ):
> PlantUML limits image width and height to 4096. There is a environment variable that you can set to override this limit: PLANTUML_LIMIT_SIZE. You have to define this variable before launching PlantUML, something like:
set PLANTUML_LIMIT_SIZE=8192 or setenv PLANTUML_LIMIT_SIZE 8192
Another way is an option in the command line:
java -DPLANTUML_LIMIT_SIZE=8192 -jar /path/to/plantuml.jar ...
Note that if you generate very big diagrams, (for example, something like 20 000 x 10 000 pixels), you can have some memory issues. The solution is to add this parameter to the java vm : -Xmx1024m.

**Workaround:**
Setting the environmental variable in a terminal window before launching the editor from that window.

I would be glad to implement this myself and do a pull request if I just had the time. 
Maybe someday I will. At least there is a viable workaround.

**Comment by krasa** [comment]
Probably the best is to just edit IntelliJ VM settings, because you need to do that for Xmx anyway.

**Comment by SJrX** [comment]
I think IntelliJ VM Settings is sub-optimal as those things get lost, and aren't part of the project settings.

**Comment by o0starshine0o** [comment]
if it is AndroidStudio,we should edit :
`/Applications/Android\ Studio.app/Contents/bin/studio.vmoptions`
add :
`-DPLANTUML_LIMIT_SIZE=24384`
in the end.

What's more, the PLANTUML_LIMIT_SIZE can be more larger

**Comment by krasa** [comment]
You can try it: https://github.com/esteinberg/plantuml4idea/releases/download/2.25.1/plantuml4idea.zip
