### ISSUE TITLE
Add a button+keyboard shortcut for "Automatically Render"

### ISSUE THREAD

**Issue by pouledodue** [esteinberg/plantuml4idea#208]
Add a button+keyboard shortcut for "Automatically Render"

Currently, "Automatically Render" is in the settings menu.

I check/uncheck it quite a lot when working on big diagrams and I'd like to be able to toggle it via its own icon+keyboard shortcut

**Comment by krasa** [comment]
You can set your own shortcut.

**Comment by pouledodue** [comment]
beautiful
