### ISSUE TITLE
Ability to use beta version of PlantUML. Customize version of plantuml library

### ISSUE THREAD

**Issue by qwazer** [esteinberg/plantuml4idea#209]
It'll be nice to have the ability to customize version of plantuml library and use beta version of plantuml.
Why?
 * Beta version of PlantUML have new interesting features like http://plantuml.com/nwdiag 
 * Also, it will save the project from a lot of issues like #190, #146  etc

**Comment by krasa** [comment]
Well, you can always download and replace it manually.

**Comment by cgi** [comment]
Very usefull tip!
For verify version chenge sugest this snipet:
```
@startuml
version
@enduml
```

**Comment by matschaffer** [comment]
I'd like this as well. Seems like the latest version of graphiviz from homebrew (2.44.1) is no longer compatible with the `plantuml.1.2020.9.jar` that this plugin ships with.

I tried swapping in 2020.11 which seems to work from the command line, but I just get nothing. Maybe incompatible with the plugin's code.

**Comment by krasa** [comment]
Fixed by https://github.com/esteinberg/plantuml4idea/issues/273

I will release it after some testing, you can try it: https://github.com/esteinberg/plantuml4idea/releases/tag/3.00
