### ISSUE TITLE
MindMap diagram support?

### ISSUE THREAD

**Issue by linux-china** [esteinberg/plantuml4idea#212]
Mindmap diagram has been supported on 2019.1    http://plantuml.com/mindmap-diagram

```
@startmindmap
* Debian
** Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio
@endmindmap
```

**Comment by blademainer** [comment]
+1

**Comment by krasa** [comment]
It should work, just not in java comments.
https://github.com/esteinberg/plantuml4idea/blob/80ffda94fd25da047c067dd3cf4dc5f66e77bc7c/src/org/plantuml/idea/plantuml/PlantUml.java#L107
