### ISSUE TITLE
PlantUML view scaling on 125% DPI looks bad (Windows 10)

### ISSUE THREAD

**Issue by anders** [esteinberg/plantuml4idea#213]
Hi, I couldn't find a similar issue so I hope this hasn't been reported before.

The PlantUML view looks bad on Windows 10 with 125% DPI set (Settings -> Display -> Scale and layout -> 125%). A screenshot is worth a thousand words:

![screenshot of broken DPI](https://i.imgur.com/2jRAaNV.png)

I tried to investigate this myself by cloning this repository, then run the plugin via Run configurations (plugin type). But when I do that, the problem is gone! I lack the necessary knowledge to solve this.

Version details:
````
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
JRE: 11.0.2+9-b159.30 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
````

**Comment by krasa** [comment]
Same here. Really strange. 
If you save the image to the disk, then it looks fine, so it must be only the displaying that is broken.

**Comment by krasa** [comment]
You can debug it if you use Jetbrains JDK - https://bintray.com/jetbrains/intellij-jdk/openjdk11-windows-x64#files -> jbrsdk-11-windows-x64-b96.tar.gz

**Comment by anders** [comment]
It looks a lot better now, thanks! The image is still scaled but not horrible to look at anymore.

**Comment by krasa** [comment]
I'll fix it more...

**Comment by krasa** [comment]
There is only a small problem now, copy to clipboard is broken with Jetbrains JRE 
https://youtrack.jetbrains.com/issue/JBR-1326
