### ISSUE TITLE
Issues for diagrams within Markdnown (ref #195)

### ISSUE THREAD

**Issue by paulvi** [esteinberg/plantuml4idea#215]
Markdown support #195 cannot be closed,  
as there are some issues:

- when markdownfile has several diagrams,  
only one is displayed, and it is  selected random, or by unknown logic.

Markdnown
![image](https://user-images.githubusercontent.com/1614482/55458566-de982a80-561f-11e9-8efc-aba7e42e65f4.png)

Source example

Sequence diagram
    
    ```plantuml
    Alice -> Bob: Authentication Request
    Bob --> Alice: Authentication Response
    
    Alice -> Bob: Another authentication Request
    Alice <-- Bob: Another authentication Response
    ```
    
    Component diagram within @startuml/@enduml
    
    ```plantuml
    @startuml
    package "FaceServer" {
    
        component SecondDb
    
    }
    @enduml
    ```
    
    Component diagram
    
    ```plantuml
    package "FaceServer" {
    
        component MainModule
    
    }
    ```

Rendered by GitHub as:

Sequence diagram

```plantuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
```

Component diagram within @startuml/@enduml

```plantuml
@startuml
package "FaceServer" {

    component SecondDb

}
@enduml
```

Component diagram

```plantuml
package "FaceServer" {

    component MainModule

}
```

**Comment by krasa** [comment]
Caret position defines which diagram is displayed. 
The diagram must have start/end tag.

**Comment by paulvi** [comment]
1. Caret position does not matter IDEA CE 2018.3.6
(I put it on other line and press within PlantUML view refresh or reload icon)

2. Adding @startuml to first sequence diagram, does not make appear

**Comment by paulvi** [comment]
OK, confirmed:

Diagram must have `@startuml` and `@enduml`, then when caret is on it, it will be shown in PlantUML view
