### ISSUE TITLE
Copy to clipboard generates blank image

### ISSUE THREAD

**Issue by slickmb** [esteinberg/plantuml4idea#217]
Installed new version from scratch on a new machine and am finding that when I click the "Copy Current Diagram to Clipboard" button that I get a blank image in my clipboard.  The image is the right dimensions, but completely blank.

Notes: 

- PlantUML version 2.13.12
- WebStorm 2019.1 Build #WS-191.6183.63, built on March 21, 2019
   JRE: 1.8.0_202-release-1483-b39 x86_64
   JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
   macOS 10.14.3
- dot - graphviz version 2.40.1 (20161225.0304)
- Saving the image to disk works fine (as long as I provide an extension in the file name)
- The diagrams are rendered and displayed correctly in webstorm
- I installed graphviz using brew
- I've tried with the `GRAPHVIZ_DOT` env var set, and unset.  my binary is in the standard brew install location (`/usr/local/bin/dot`)
- seems to affect all types of diagrams (tested with sequence, class, and component diagrams)
- the feature worked on my old machine with the latest version of webstorm and the previous version of the PlantUML plugin

**Comment by slickmb** [comment]
Manually downgrading the plugin to 2.12.1 seems to resolve the issue.

**Comment by krasa** [comment]
Do you have retina or some scaling enabled?
It is probably related to this https://youtrack.jetbrains.com/issue/JBR-1326
I will have to make some workaround

**Comment by slickmb** [comment]
I do have a retina display.  Scale was set to 1:1.

**Comment by krasa** [comment]
Please try this: [plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/3069371/plantuml4idea.zip)
(simply dragging the file into the editor should install it)
