### ISSUE TITLE
Automatically render when returning to file if included files are changed (don't use cache)

### ISSUE THREAD

**Issue by studgeek** [esteinberg/plantuml4idea#218]
I am seeing the following if main.puml depends on include.puml:
1. open main.puml
  a) main.puml rendered automatically
2. open, edit, and save include.puml
  a) include.puml rendered automatically
3. return to main.puml
  a) main.puml is cached so it does not re-render and changes to include.puml are not shown

In 3a I would expect main.puml to be re-rendered since its included file has changed.

Setting cache size to 0 seems to fix things, which implies over-aggressive caching is the problem. Thx!

**Comment by krasa** [comment]
I see, you use @startuml in your included file too. It worked fine for me because I do not.

Thanks for reporting it.

**Comment by krasa** [comment]
Could you please try the fix?
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/3105128/plantuml4idea.zip)
-just download and drag it into the editor

**Comment by studgeek** [comment]
Yes, that fixes it. Thanks for the quick response!
