### ISSUE TITLE
Adding !preprocessorV2 to PlantUML config causes Syntax Error

### ISSUE THREAD

**Issue by studgeek** [esteinberg/plantuml4idea#219]
If I add the new !preprocessorV2 directive to the "PlantUML config" in preference I seem to get a red Syntax Error in every diagram.

**Comment by studgeek** [comment]
Background on is at !preprocessorV2 http://plantuml.com/preprocessing-v2 and it it also mentioned in http://forum.plantuml.net/9381/syntax-error-w-with-includesub-with-comments-since-2018-11?show=9412#c9412.

**Comment by krasa** [comment]
works fine for me with 2.14, but you can always try to upgrade plantuml in 
`.<IdeaIC2019.1>\config\plugins\plantuml4idea\lib`

**Comment by krasa** [comment]
oh, in config or included file. Well, still plantuml bug, nothing to do here.

**Comment by studgeek** [comment]
I had assumed that option was something that the plugin did, but now that I knew to look I found the following. So are the contents of that file passed to plantuml using --config? If so, I can use that to reproduce for plantuml team.
http://forum.plantuml.net/4266/configuration-file-specification

**Comment by krasa** [comment]
We do not use the command line, but `--config` and `PlantUML config` is the same thing.

I think there is no problem anymore:
http://forum.plantuml.net/9381/syntax-error-w-with-includesub-with-comments-since-2018-11?show=9420#c9420

**Comment by studgeek** [comment]
It is still a problem on the GA release 2015.1, but it is going away once they fully move to the preprocessor so I agree it is low priority and a plantuml issue anyway.

**Comment by krasa** [comment]
probably obsolete now
