### ISSUE TITLE
Error writing diagram

### ISSUE THREAD

**Issue by alanhg** [esteinberg/plantuml4idea#225]
![image](https://user-images.githubusercontent.com/9245110/58701845-b128ec80-83d6-11e9-8436-d5e2d9aec8e2.png)
![image](https://user-images.githubusercontent.com/9245110/58701871-c6058000-83d6-11e9-905c-76447c275864.png)
I can't export diagram

**Comment by krasa** [comment]
Cannot reproduce.
Could you post a screenshot of the file chooser dialog before it fails?

**Comment by alanhg** [comment]
> Cannot reproduce.
> Could you post a screenshot of the file chooser dialog before it fails?

![image](https://user-images.githubusercontent.com/9245110/58741974-b592eb00-8452-11e9-8ce9-6f83cbe2559b.png)

**Comment by krasa** [comment]
Hmm, it was supposed to look like this:
![image](https://user-images.githubusercontent.com/1160875/58742399-32a76b80-8425-11e9-81cf-911923b751ee.png)

**Comment by krasa** [comment]
You can update.

**Comment by krasa** [comment]
I will have to fix it more...

**Comment by krasa** [comment]
Now it should be ok.

**Comment by alanhg** [comment]
@krasa after update plugin.it's ok, thank you!
