### ISSUE TITLE
Setting for additional plantuml.include.path

### ISSUE THREAD

**Issue by sl-nathanbu** [esteinberg/plantuml4idea#228]
Currently; util.Utils sets the "plantuml.include.path" to only the currently selected files' parent directory ( via UIUtils::getSelectedDir ). 

A setting which allowed additional include paths, would help when working on more complex diagrams with shared resources.

The closest workaround is to prepackage the include/ structure and !import the zip file

**Comment by krasa** [comment]
You want a global settings, or per file by e.g putting it as a comment inside the diagram?

**Comment by sl-nathanbu** [comment]
Just some way to pass an additional path to System::setProperty("plantuml.include.path").
For my usage; a per-project setting would be preferable; but a true global would be functional.

**Comment by bwoester** [comment]
Same here, we're using it to generate C4 diagrams (see https://github.com/RicardoNiepel/C4-PlantUML), so we're having different includes like the follwoing in almost all our diagrams:

```
!include path/to/C4_Container.puml
!include path/to/C4_Context.puml
```

Without being able to configure the include path, we're left with
- include an URL like `!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml`, which doesn't work when offline or might trigger rate limits (not sure if we'd hit them)
- include relative pathes like `!include ../../../C4_Context.puml`, which becomes tedious as the folder structure grows or once you start moving files around
- come up with a workaround like `!include %getenv("C4_HOME")/C4_Context.puml`, which I didn't test yet. Not sure if that would work at all.

If we could simply configure the include path, everybody in our team could simply point it to include their local clone of the C4-PlantUML repo and all our plantuml files could simply

```
!include C4_Container.puml
!include C4_Context.puml
```

**Comment by krasa** [comment]
You can try it: https://github.com/esteinberg/plantuml4idea/releases/download/2.25.1/plantuml4idea.zip
