### ISSUE TITLE
syntax highlighting in editor

### ISSUE THREAD

**Issue by nnar1o** [esteinberg/plantuml4idea#230]
can you please add the same highlighting as i.e. in visual studio code? 

![image](https://user-images.githubusercontent.com/38096038/61928839-01a56c00-af7a-11e9-8765-eb0a191bd820.png)

on intellij it looks like this (no syntax highliting):
![image](https://user-images.githubusercontent.com/38096038/61928892-2ef21a00-af7a-11e9-8ad2-a09079604172.png)

**Comment by krasa** [comment]
#179
