### ISSUE TITLE
Diagram not rendered when using LAYOUT_WITH_LEGEND

### ISSUE THREAD

**Issue by raulcodurance** [esteinberg/plantuml4idea#231]
Hi all,

I updated to the last version of the plugin and now, LAYOUT_WITH_LEGEND, does not let the diagram be rendered.

I attach the error screenshot.
![Screenshot 2019-07-29 at 11 11 51](https://user-images.githubusercontent.com/48439443/62036248-bd240580-b1f1-11e9-9aad-6212ab60c044.png)

thanks

**Comment by krasa** [comment]
plantuml bug/feature?
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuV9nZFGF3OaFzmpnYFTnTNVrS-7YSifFKj2rKt3CoKnELR1Io4ZDoSddSaZDIm5g0000

**Comment by kula99** [comment]
use parenthesis, LAYOUT_WITH_LEGEND()
