### ISSUE TITLE
Occasional NullPointerException when typing in PlantUML file

### ISSUE THREAD

**Issue by danielschenk** [esteinberg/plantuml4idea#232]
I got this twice within one hour, while working in a PlantUML document in PyCharm. It appears to have started only after I upgraded PyCharm from 2019.2 to 2019.2.1. I'm using the 2.19.1 version of the plugin.
```
java.lang.NullPointerException
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$ThreadStream.run(ProcessRunner.java:252)
```

**Comment by krasa** [comment]
https://forum.plantuml.net/9922/nullpointerexception

**Comment by eugene-borovov** [comment]
I got the same issue (plugin version 2.52.2). It occurs on every PlantUML syntax error.

**Comment by krasa** [comment]
please comment here: https://forum.plantuml.net/9922/nullpointerexception

**Comment by krasa** [comment]
should be fixed in recent version
