### ISSUE TITLE
Don't ask for permission to override file on export

### ISSUE THREAD

**Issue by uhafner** [esteinberg/plantuml4idea#238]
When I am exporting the diagram and the file already exists then a dialog appears that asks for permission to overwrite it. This is somewhat cumbersome, the UI would be more elegant if it simply would overwrite the file. There is a version management integration and a local history in IntelliJ which helps users to restore overwritten files.

**Comment by krasa** [comment]
That is handled by IntelliJ itself, it will be better to not reimplement it.
