### ISSUE TITLE
Not possible to save multiple diagrams described in a single file

### ISSUE THREAD

**Issue by metomas** [esteinberg/plantuml4idea#241]
If more than one diagram is described in a single file (example below), clicking on `Save All Diagrams in Current File` generates the current diagram only.

```
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml

@startuml
John -> Jane: Authentication Request
Jane --> John: Authentication Response

John -> Jane: Another authentication Request
John <-- Jane: another authentication Response
@enduml
```

Intellij IDEA 2019.1.3 (Ultimate Edition)
PlantUML Integration v2.21.0

**Comment by krasa** [comment]
It should probably be renamed to 'Save All Diagrams'.

**Comment by metomas** [comment]
@krasa what do you mean by saying all pages?

**Comment by krasa** [comment]
```
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
  
newpage
  
John -> Jane: Authentication Request
Jane --> John: Authentication Response

John -> Jane: Another authentication Request
John <-- Jane: another authentication Response
@enduml
```

2 pages = 2 diagrams = 2 images

**Comment by metomas** [comment]
Got it. Thanks for explanation.

Just to close this thread this is what gets generated for your example.

![image](https://user-images.githubusercontent.com/16761903/67276700-8c3c2f80-f4c5-11e9-9de6-014354387263.png)
![image](https://user-images.githubusercontent.com/16761903/67276715-9100e380-f4c5-11e9-9e34-7d974c94f870.png)

I suppose that Alice/Bob and John/Jane should be on separate diagrams.
