### ISSUE TITLE
Not possible to save diagram with intellij ultimate 2019.2.3 on macos

### ISSUE THREAD

**Issue by idefixcert** [esteinberg/plantuml4idea#242]
When I click save current diagram only intellij freezes and I have to kill the application.

**Comment by krasa** [comment]
any threaddumps in the log folder?

**Comment by idefixcert** [comment]
no did't find anything,

but I saw, actually if I say save, then I get the save dialog,
and if I cancel the idea also freezes.

Regards Chris

**Comment by krasa** [comment]
that looks like a platform issue

**Comment by clemensbartz** [comment]
**Cannot** confirm this issue for 2019.2.4.
