### ISSUE TITLE
Plugin is broken with using markdown code fence and PUML Fragment editor

### ISSUE THREAD

**Issue by totodo713** [esteinberg/plantuml4idea#243]
hi 

NullPointerException occurred when I edited my .md code fence with PUML Fragment editor.
Is the cause of this exception a double launch of PlantUML (or dot)?

![image](https://user-images.githubusercontent.com/35787394/67736425-f49d8a80-fa4a-11e9-855b-a9658b7a2a9f.png)

**Comment by krasa** [comment]
File's directory was null, strange.

**Comment by totodo713** [comment]
hi krasa.

Thank you for fixing too quickly!
It is comfortable to use.
