### ISSUE TITLE
Please tag newer releases

### ISSUE THREAD

**Issue by jonathonf** [esteinberg/plantuml4idea#244]
The tags in GitHub stop with version 2.16.0 but the release version is now up to [2.22.0](https://plugins.jetbrains.com/plugin/7017-plantuml-integration/update/71296).

Could you please tag releases in GitHub too?

**Comment by krasa** [comment]
Just out of curiosity, what for do you need it?

**Comment by jonathonf** [comment]
For example, it makes it much easier to track new releases than the Jetbrains plugin page (which has a weird [AJAX JSON-based deferred loading](https://plugins.jetbrains.com/api/plugins/7017/updates?channel=) rather than a standard HTML page or feed).

**Comment by krasa** [comment]
thanks, interesting.
