### ISSUE TITLE
Feature request: Allow preview renderer to be "embedded" in editor tab

### ISSUE THREAD

**Issue by christophercurrie** [esteinberg/plantuml4idea#246]
Because the renderer is a separate toolbar window, when it's expanded it compresses the editor window causing some editor tabs to be hidden, making it a little more awkward to switch between files.

If the preview window was nested in the editor, in a similar way to the built-in Markdown previewer, editor tab placement would be unaffected.

**Comment by krasa** [comment]
The one advangate the current way has, is that it works anywhere, for any embedded code. The editor would work only for associated file extensions.

**Comment by krasa** [comment]
Duplicates #299
