### ISSUE TITLE
commented text should have uniform color

### ISSUE THREAD

**Issue by skewty** [esteinberg/plantuml4idea#247]
Comments should have all text uniform / the same color.  
Currently, reserved / keywords are colored differently

![Screenshot from 2019-12-12 07-39-31](https://user-images.githubusercontent.com/9087223/70726248-9f43d280-1cb2-11ea-9f96-bdf7ba7de283.png)

Example: In the screen capture above, I would expect the word `activate` to be gray

**Comment by skewty** [comment]
Perhaps this is related..   the colored / reserved / special words aren't always matching

![Screenshot from 2019-12-13 16-28-34](https://user-images.githubusercontent.com/9087223/70840240-d1922480-1dc5-11ea-9d5e-b77e123ecf3a.png)

notice how `package` and `class` are not being recognized

**Comment by skewty** [comment]
Is this the same as #39?

**Comment by krasa** [comment]
yes, and  #17 #179

**Comment by robert-franz** [comment]
Another issue is e.g. when writing notes and having one of the keywords inside the note. Then e.g. all the keywords are highlighted. In the end this definately is not a problem but it would be much nicer having no coloring there.
