### ISSUE TITLE
Can't zoom dot files

### ISSUE THREAD

**Issue by onetom** [esteinberg/plantuml4idea#248]
When I try to use PlantUML to simply render a directed graph using DOT syntax, eg:

```
@startdot
digraph g {
  node1 -> node2 -> node3
}
@enddot
```

the graph appears, but nothing happens when I'm clicking on the zoom controls in the PlantUML tool window.

The built-in UML examples got rendered as expected and they can be zoomed in and out too.

I've tried it with `nix-env -i plantuml graphviz` and `brew install plantuml`, but neither versions work
with the latest 2.22.0 PlantUML plugin.

```
$ dot -v < /dev/null
dot - graphviz version 2.43.0 (0)
libdir = "/usr/local/Cellar/graphviz/2.42.2/lib/graphviz"
Activated plugin library: libgvplugin_dot_layout.6.dylib
Using layout: dot:dot_layout
Activated plugin library: libgvplugin_core.6.dylib
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
        /usr/local/Cellar/graphviz/2.42.2/lib/graphviz/config6
                was successfully loaded.
    render      :  dot dot_json fig gd json json0 map mp pic pov ps quartz svg tk visio vml vrml xdot xdot_json
    layout      :  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout  :  textlayout
    device      :  bmp canon cgimage cmap cmapx cmapx_np dot dot_json eps exr fig gd gd2 gif gv icns ico imap imap_np ismap jp2 jpe jpeg jpg json json0 mp pct pdf pic pict plain plain-ext png pov ps ps2 psd sgi svg svgz tga tif tiff tk vdx vml vmlz vrml wbmp xdot xdot1.2 xdot1.4 xdot_json
    loadimage   :  (lib) bmp eps gd gd2 gif jpe jpeg jpg pdf png ps svg xbm
```

```
$ plantuml -version
PlantUML version 1.2020.00 (Sat Jan 11 20:30:53 HKT 2020)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Java Version: 13.0.1+9
Operating System: Mac OS X
Default Encoding: US-ASCII
Language: en
Country: HK
Machine: lynx.local
PLANTUML_LIMIT_SIZE: 4096
Processors: 16
Max Memory: 21,474,836,480
Total Memory: 1,350,565,888
Free Memory: 1,341,099,264
Used Memory: 9,466,624
Thread Active Count: 1

The environment variable GRAPHVIZ_DOT has been set to /usr/local/opt/graphviz/bin/dot
Dot executable is /usr/local/opt/graphviz/bin/dot
Dot version: dot - graphviz version 2.43.0 (0)
Installation seems OK. File generation OK
```

**Comment by krasa** [comment]
https://forum.plantuml.net/11351/unable-to-scale-dot-diagram?show=11351#q11351

**Comment by patkujawa-wf** [comment]
What about being able to zoom to see the error message when the diagram has a syntax error? That's actually more of my use case - it's so small that I can't read what it says and also can't zoom in to read it :(. Is that something that can be fixed here?

**Comment by krasa** [comment]
@patkujawa-wf you have a Retina or use 200% DPI?

**Comment by patkujawa-wf** [comment]
@krasa yes, a retina display. Though even on my external monitor (non-retina) it is small, and I don't have any special DPI setting. If anything, I typically set things so they  are larger, not smaller, with  my old, tired eyes :D

**Comment by krasa** [comment]
I will create an issue for PlantUML, and maybe also try to implement rendering using SVG, that would solve everything.

**Comment by onetom** [comment]
This seems to be working now, but not sure why.
My guess would be that SVG support has been added, maybe by [this](https://github.com/esteinberg/plantuml4idea/commit/5c65626ec03a4835793a8f6186f4995de28e43a3) commit?

But can't really tell, because neither https://github.com/esteinberg/plantuml4idea/releases nor https://github.com/esteinberg/plantuml4idea/blob/master/CHANGELOG.md is being updated :(

**Comment by krasa** [comment]
And do you need to?

Updating https://github.com/esteinberg/plantuml4idea/releases is too much work
https://github.com/esteinberg/plantuml4idea/blob/master/CHANGELOG.md is a new thing.

Changelog is here: https://plugins.jetbrains.com/plugin/7017-plantuml-integration/versions/stable/301286

**Comment by onetom** [comment]
@krasa I like to read changelogs, because it's an easier way keep up with the development progress, then reading code diffs, so it would be nice to see just a little bit more detail.

I like how IntelliJ summarizes their changes:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/56646/235343520-b21efdf4-93bf-455e-af00-258b4f94f2bc.png">

which is similar to how Clojure does it too:
https://clojure.org/releases/devchangelog

Either way, it's a fantastic plugin, thank you and see my appreciation in your Github Sponsor history! :)

**Comment by krasa** [comment]
Thank you!

Those projects are on a different level, but I will try :-)
