### ISSUE TITLE
diagrams with !include <file> do not reload as expected

### ISSUE THREAD

**Issue by skewty** [esteinberg/plantuml4idea#251]
```uml
@startuml
' B class comes from external
!include external.puml
class A {
  + name: string
}
A --> B
@enduml
```
Load up external.puml in IDE and make a change.  The diagram updates right away.
Go back to the previous diagram with !include.  Click the [Reload] button.
The change is not picked up (it happens eventually).  
Restarting the IDE makes it work right away obviously.

**Comment by skewty** [comment]
I set cache to `0` and restarted my IDE.  It still doesn't work as expected.

When I make a change to external.puml with "Automatically Render" enabled it shows the change immediately.  When I switch to the other drawing and click [Reload] button it does not pick up the change.

If I go back to external.puml and Ctrl-S (Save All), go back to other drawing and click [Reload] button it does pick up the change.

Is this a file write delay / caching by IDE issue that cannot be easily solved perhaps?  How does dot render the new data if the file doesn't have the newest contents?  Does it get data from a pipe and not from file?

**Comment by krasa** [comment]
Includes are loaded from HDD, so the IDE needs to save them before rendering, but apparently it no longer works:

https://forum.plantuml.net/10952/blockumlbuilder%23getincludedfiles-no-longer-works

**Comment by krasa** [comment]
you can try this, it has new beta plantuml jar: https://github.com/esteinberg/plantuml4idea/releases/download/2.23.0/plantuml4idea.zip

**Comment by skewty** [comment]
That did it!  Thanks for such a quick response / fix.

Does caching still need to be set to `0`?  Was that step a troubleshooting one?

**Comment by krasa** [comment]
No, caching should work fine.
