### ISSUE TITLE
125% DPI Scaling on multiple monitors looks bad (Windows 10)

### ISSUE THREAD

**Issue by dubreuia** [esteinberg/plantuml4idea#254]
Hello guys,

Thank you for doing this plugin, it is amazing!

My issue is the same as #213, #182, #148. I don't know if it is a regression or not (I tried downloading version 2.13.0 but it doesn't work anymore, and hello @krasa !), at scaling 125% on Windows 10, the preview doesn't look good. Here is at 100% and 125% scaling:

![plantuml-preview-windows-10-scaling-100-beautiful](https://user-images.githubusercontent.com/657731/80493402-a4ee3c00-8965-11ea-952c-08140bdace77.PNG)
![plantuml-preview-windows-10-scaling-125-ugly](https://user-images.githubusercontent.com/657731/80493130-488b1c80-8965-11ea-9c04-1e08645d37ed.PNG)

Thanks,

```
IntelliJ IDEA 2020.1.1 Preview (Ultimate Edition)
Build #IU-201.7223.18, built on April 16, 2020
Licensed to Intellij Save Actions Plugin / Alexandre Dubreuil
Subscription is active until September 26, 2020
For non-commercial open source development only.
Runtime version: 11.0.6+8-b765.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1994M
Cores: 4
Non-Bundled Plugins: IdeaVIM, PlantUML integration, com.codestream.jetbrains-codestream, com.dubreuia, Pythonid, org.jetbrains.kotlin
```

**edit** I've zoomed in both images to see the differences

**Comment by krasa** [comment]
Works fine for me, could you paste your source code? Did you log-off after changing to 125%?

![image](https://user-images.githubusercontent.com/1160875/80494648-30b49800-8967-11ea-83ba-9e2e612fdd95.png)
```
IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.max.recent.projects=1001

```

**Comment by dubreuia** [comment]
Found the problem: I have 2 monitors, one of them doesn't have the same scaling (100% and 125%). When I drag the Intellij window from the 125% monitor to the 100% monitor, the diagram gets all blurry. Weird, because the rest of the content is OK (I really don't understand how scaling works).

Thank you for your answer @krasa, I'm closing this issue.

**Comment by krasa** [comment]
Not sure if it should work or not.

It is done by:
https://github.com/esteinberg/plantuml4idea/blob/0104ea8dba00983991d661fec1eb6215c1431e9e/src/org/plantuml/idea/toolwindow/PlantUmlImageLabel.java#L94-L95

relevant: 
https://github.com/JetBrains/intellij-community/blob/4f20b03caca11a3108607109cbbe2443d10dd425/platform/util/ui/src/com/intellij/ui/scale/ScaleType.java#L66-L81 
https://youtrack.jetbrains.com/issue/IDEA-141456

I did not really study it, but if you run in JRE managed mode, it should probably work.

**Comment by DidierLoiseau** [comment]
@krasa Is it supposed to work in dual-screen mode? PlantUML seems to only take into account the scale of the main display (laptop screen), in my case 125%. On the secondary display (external screen), which is set to 100%, diagrams are blurry, except if I set it to 125% as well.

I swapped the primary and secondary display, and now I have it sharp on the external screen (at 100%) and blurry on the laptop screen (at 125%).

I have set the [JRE managed HiDPI mode](https://intellij-support.jetbrains.com/hc/en-us/articles/360007994999-HiDPI-configuration) (`-Dsun.java2d.uiScale.enabled=true`) as you suggested, but it does not seem to make a difference, even after refreshing the image.

Should I create a separate issue for dual-screen usage? Although, it seems it was the original issue @dubreuia, so maybe we could keep this one open and rename it.

**Comment by krasa** [comment]
I may have a fix, but cannot reproduce it, could you try this? 
(Drag it into the editor.)
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/4603513/plantuml4idea.zip)

**Comment by DidierLoiseau** [comment]
Thanks @krasa, that seems to fix it for me – I just have to refresh the diagram when moving from one screen to the other.

**Comment by krasa** [comment]
Good, thanks!
