### ISSUE TITLE
Issue with attributes SIDES of TABLE or TD

### ISSUE THREAD

**Issue by neooblaster** [esteinberg/plantuml4idea#255]
Hi Team,

I encounter an issue (minor) with PlantUML **2.24.0** under PhpStorm **2020.1**.
The value `LR` or `RL` will not work.
Their is no issue if `T` or `B` is used with.

Please find below a screenshot showing the issue.
For the issue I add empty cell to separated cases :

![image](https://user-images.githubusercontent.com/22078558/80648851-31d1ec00-8a71-11ea-8917-c10f77d28ff4.png)

Source Code :
````plantuml
@startuml
digraph ZHUM_AUTO {
    // Global Configuration
    node [
        shape=box
    ]

    // Nodes Configurations
    Manual [
        shape=none; label=<<table border="0" cellborder="1" cellspacing="0">
        <tr><td bgcolor="red">    </td><td> Manuel </td></tr>
        </table>>;
    ];
    Auto [
        shape=none; label=<<table border="0" cellborder="1" cellspacing="0">
        <tr><td bgcolor="green">    </td><td> Auto </td></tr>
        </table>>;
    ];
    ME21N [
        shape=none; label=<<table border="0" cellspacing="0">
        <tr>
            <td bgcolor="red" border="1"> 1 </td>
            <td border="1"> Create Order </td>
            <td border="1"> ME21N </td>
        </tr>
        <tr><td colspan="3" align="left" border="1" sides="LRT"> A </td></tr>
        <tr><td colspan="3" align="left" border="0" sides="">   </td></tr>
        <tr><td colspan="3" align="left" border="1" sides="L"> L Alone </td></tr>
        <tr><td colspan="3" align="left" border="0" sides="">  </td></tr>
        <tr><td colspan="3" align="left" border="1" sides="R"> R Alone </td></tr>
        <tr><td colspan="3" align="left" border="0" sides="">  </td></tr>
        <tr><td colspan="3" align="left" border="0" sides="RL"> RL Issue </td></tr>
        <tr><td colspan="3" align="left" border="0" sides="">  </td></tr>
        <tr><td colspan="3" align="left" border="1" sides="LRT"> RLT No issue </td></tr>
        <tr><td colspan="3" align="left" border="0" sides="">  </td></tr>
        <tr><td colspan="3" align="left" border="1" sides="LRB"> RLB No Issue </td></tr>
        <tr><td colspan="3" align="left" border="0" sides="">  </td></tr>
        <tr><td colspan="3" align="left" border="1" sides="LRB"> B </td></tr>
        </table>>;
    ];
    ME29N [];
    MIGO [];
    ZAUD [];
    ZAUT [];

    // Nodes Links
    subgraph cluster_legend {
        label = "Legend";
        Manual Auto;
    }

    subgraph cluster_YMM_INBOUND_AUTO {
        label = "YMM_INBOUND_AUTO";
        AB
    }


}
@enduml
````

This Tool indicates that must works : 

[GraphvizOnline](https://dreampuf.github.io/GraphvizOnline/#digraph%20ZHUM_AUTO%20%7B%0D%0A%20%20%20%20%2F%2F%20Global%20Configuration%0D%0A%20%20%20%20node%20%5B%0D%0A%20%20%20%20%20%20%20%20shape%3Dbox%0D%0A%20%20%20%20%5D%0D%0A%0D%0A%20%20%20%20%2F%2F%20Nodes%20Configurations%0D%0A%20%20%20%20Manual%20%5B%0D%0A%20%20%20%20%20%20%20%20shape%3Dnone%3B%20label%3D%3C%3Ctable%20border%3D%220%22%20cellborder%3D%221%22%20cellspacing%3D%220%22%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20bgcolor%3D%22red%22%3E%20%20%20%20%3C%2Ftd%3E%3Ctd%3E%20Manuel%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3C%2Ftable%3E%3E%3B%0D%0A%20%20%20%20%5D%3B%0D%0A%20%20%20%20Auto%20%5B%0D%0A%20%20%20%20%20%20%20%20shape%3Dnone%3B%20label%3D%3C%3Ctable%20border%3D%220%22%20cellborder%3D%221%22%20cellspacing%3D%220%22%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20bgcolor%3D%22green%22%3E%20%20%20%20%3C%2Ftd%3E%3Ctd%3E%20Auto%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3C%2Ftable%3E%3E%3B%0D%0A%20%20%20%20%5D%3B%0D%0A%20%20%20%20ME21N%20%5B%0D%0A%20%20%20%20%20%20%20%20shape%3Dnone%3B%20label%3D%3C%3Ctable%20border%3D%220%22%20cellspacing%3D%220%22%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%20bgcolor%3D%22red%22%20border%3D%221%22%3E%201%20%3C%2Ftd%3E%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%20border%3D%221%22%3E%20Create%20Order%20%3C%2Ftd%3E%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Ctd%20border%3D%221%22%3E%20ME21N%20%3C%2Ftd%3E%0D%0A%20%20%20%20%20%20%20%20%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%221%22%20sides%3D%22LRT%22%3E%20A%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%220%22%20sides%3D%22%22%3E%20%20%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%221%22%20sides%3D%22L%22%3E%20L%20Alone%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%220%22%20sides%3D%22%22%3E%20%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%221%22%20sides%3D%22R%22%3E%20R%20Alone%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%220%22%20sides%3D%22%22%3E%20%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%221%22%20sides%3D%22RL%22%3E%20RL%20Issue%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%220%22%20sides%3D%22%22%3E%20%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%221%22%20sides%3D%22LRT%22%3E%20RLT%20No%20issue%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%220%22%20sides%3D%22%22%3E%20%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%221%22%20sides%3D%22LRB%22%3E%20RLB%20No%20Issue%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%220%22%20sides%3D%22%22%3E%20%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3Ctr%3E%3Ctd%20colspan%3D%223%22%20align%3D%22left%22%20border%3D%221%22%20sides%3D%22LRB%22%3E%20B%20%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%20%20%20%20%20%20%20%20%3C%2Ftable%3E%3E%3B%0D%0A%20%20%20%20%5D%3B%0D%0A%20%20%20%20ME29N%20%5B%5D%3B%0D%0A%20%20%20%20MIGO%20%5B%5D%3B%0D%0A%20%20%20%20ZAUD%20%5B%5D%3B%0D%0A%20%20%20%20ZAUT%20%5B%5D%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20Nodes%20Links%0D%0A%20%20%20%20subgraph%20cluster_legend%20%7B%0D%0A%20%20%20%20%20%20%20%20label%20%3D%20%22Legend%22%3B%0D%0A%20%20%20%20%20%20%20%20Manual%20Auto%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20subgraph%20cluster_YMM_INBOUND_AUTO%20%7B%0D%0A%20%20%20%20%20%20%20%20label%20%3D%20%22YMM_INBOUND_AUTO%22%3B%0D%0A%20%20%20%20%20%20%20%20AB%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%0D%0A%7D)

![image](https://user-images.githubusercontent.com/22078558/80648841-2aaade00-8a71-11ea-9104-9389f64763a1.png)

Thanks a lot for your work !

Kindly Regards,
Nicols D.

**Comment by krasa** [comment]
Not a plugin issue http://www.plantuml.com/plantuml/uml/pPNTQjim583l_HG7lq2QxMeqDhNRqGLi1qnoiPOHPElK5TEa8CamA7ttwOTuhXYZtKA9BvAS7tt-98BEbJP4cV47JoWR53aymjsNNRqlTjiDF2LWdyK2Rhdi28ThAHxOC2fYc1I-9YH5k4yWFA0VoG6pJlxqcM_9SNrZs_JBvThNQY962uu9GWgy14uwvDbgPKZ74JgfAAeilKYXHywFuJA4-a1w9WPNpYVOogXyPIXqGo-vjCqAQPhxoi9GLygz0VAGi1zgjdhXNvpdbs4tuQiOZNmttq4XYjZO6xpQj_xyOTcyNVWlXZwO4l7nmk-Dvh0Cdl6A5ptN2eb1sBZCAzhzVgA-S0xnAVRIxK5awSSK26U3_SNnmSmDGJEAEakhTclHHS3-8-rYebaK1DJ_YrbM1GMN0ayeTngtrgBQSt6BI6tbv2fOQpsUYrtyTskhBJGIs9agbbwnT8hhCrOittGLVchW_XYjRpTJS5ViRkR1rWNH-AgO-AvzIezT69Kz7xL1jUSueA3mD0ducnKoI2jVIGDuDl7S9HwIpycVcL_hUhzkoiskkPccSKoFUsRlASeZFNbEhgo36_6_0000

**Comment by neooblaster** [comment]
Hello,

Oh Okay, I didn't thought you just only port PlantUML into JetBrain IDEs.
Is PlantUML has a Issue Tracker ?

**Comment by neooblaster** [comment]
Final Solution :
Graphviz for window latest version was 2.44, not 2.38 as available on the official website : 

[https://gitlab.com/graphviz/graphviz/-/issues/1706](https://gitlab.com/graphviz/graphviz/-/issues/1706)

**Comment by krasa** [comment]
That's nuts, I was running 2.38 too.

**Comment by neooblaster** [comment]
Hi @krasa ,

You can find latest version (Automatically Build) here.
You have to select your OS/Release and then go in Artefact to get .exe file or zip. 

[https://ci.appveyor.com/project/ellson/graphviz-pl238](https://ci.appveyor.com/project/ellson/graphviz-pl238)
