### ISSUE TITLE
Feature request: UML preview for PlantUML code blocks in Markdown files

### ISSUE THREAD

**Issue by TobseF** [esteinberg/plantuml4idea#256]
I often use PlantUML for documentation and add it to project README files. So it would be a great benefit to edit and view a diagram during editing it in a Markdown file. A hosting platform like GitLab can already preview the rendered Markdown in place.
### Needed
For markdwon files: Render code blocks (```) of with `plantuml` syntax in the PlantUML-Tab.
### Why
So we can write our diagram direct in place where it's needed. Otherwise we have to write the diagram in a separate `.puml`-file and copy it to the destination markdown and replace the `@startuml` by ` ``` plantuml`. And to display a written diagramm, we need these steps backwards.
#### `README.md`
``` markdown
# Some Markdown README

``` plantuml
Object <|-- ArrayList

Object : equals()
ArrayList : Object[] elementData
ArrayList : size()
`` ` 
```

**Comment by krasa** [comment]
You can try it
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/4745778/plantuml4idea.zip)

**Comment by TobseF** [comment]
👍 Great... thanks a lot, for the super fast response with update!
It works and makes my live as a dev one stepp better 🌞
