### ISSUE TITLE
When Editor tabs placed on the right, they mess up the editor layout

### ISSUE THREAD

**Issue by jpierson-vetsource** [esteinberg/plantuml4idea#259]
If Settings->Editor Tabs->Tab placement = Right then when the uml editor is open, the editor tabs appear between the UML text and the Diagram.
![plantuml_bug](https://user-images.githubusercontent.com/5347445/87691680-7dcb2d80-c750-11ea-887d-69d27213a45f.png)

**Comment by krasa** [comment]
That's just how IntelliJ works.

**Comment by krasa** [comment]
You probably want this https://github.com/esteinberg/plantuml4idea/issues/246
