### ISSUE TITLE
Question about Grammar and Gradle branches

### ISSUE THREAD

**Issue by jord1e** [esteinberg/plantuml4idea#263]
Hello,

What is the status of the `gradle` and `grammar` (syntax highlighting) branches? Is any help wanted on implementing and testing the two? The two branches are hundreds of commits behind and seem relatively complete.

If help is wanted on implementing Gradle i could also automate testing and deployment using GitHub actions <https://github.com/features/actions>.

Thanks for the work you do.

**Comment by krasa** [comment]
- grammar was never finished, https://plugins.jetbrains.com/plugin/14821-plantuml-studio seems to have grammar for every diagram type, that is probably a better way.
- gradle imho does not have much point for such small plugin. It makes compilation slower - `https://github.com/JetBrains/gradle-intellij-plugin/issues/459`,  and adds another thing that needs to be maintained. The project setup is done faster manually anyway, and automatic testing is not needed, fixing issues is. :)
