### ISSUE TITLE
%filename() and %dirpath() return empty values

### ISSUE THREAD

**Issue by bondden** [esteinberg/plantuml4idea#266]
Built-in PlantUML functions `%filename()` and `%dirpath()` return empty values.

Steps to reproduce:

1. Environment: 

- Linux version, but there's a mention of the same behavior on Windows (https://forum.plantuml.net/9434/questions-regarding-preprocessorv2)
- Plugin version: 2.25.2
- IDE Version: WebStorm 2020.2.3 Build #WS-202.7660.23, built on September 30, 2020

2. Example code:

![s_20201028_224406](https://user-images.githubusercontent.com/5232392/97460718-11b2b500-194e-11eb-923c-94c75ec9beae.png)

**Comment by krasa** [comment]
%dirpath() does not work for me even from the command line for v1.2020.19 on Win10
