### ISSUE TITLE
flow diagram does not render

### ISSUE THREAD

**Issue by 3bdl1** [esteinberg/plantuml4idea#268]
hello,
i am trying to use plantuml extention to render a flow diagram, by using just this simple snippet:
`@startuml
(*) --> "First Action"
-->[You can put also labels] "Second Action"
--> (*)
@enduml`

i have this error
![image](https://user-images.githubusercontent.com/10292081/99527662-72596e80-299d-11eb-896a-0776fd91a399.png)

**Comment by krasa** [comment]
Install  Graphviz.

**Comment by 3bdl1** [comment]
thank you ! 
worked great
