### ISSUE TITLE
IDE Export Settings throws NotDirectoryException

### ISSUE THREAD

**Issue by rhutzel** [esteinberg/plantuml4idea#272]
Open IntelliJ's File menu and select "Manage IDE Settings" and "Export Settings...". Choose any options and destination, then click OK. I receive the following error message in a pop-up dialog:

> Error Writing File
Error writing settings.
java.nio.file.NotDirectoryException:
/Users/<username>/Library/Application Support/JetBrains/IntelliJIdea2020.3/options/plantuml.cfg

My `/Users/<username>/Library/Application Support/JetBrains/IntelliJIdea2020.3/options/plantuml.cfg` exists as an XML file, and not a directory.

I'm using IntelliJ IDEA 2020.3 Ultimate Edition on macOS.

**Comment by deeppunster** [comment]
It appears that all other plugin settings files in the .../options directory are .xml files.  The plantuml settings file is a .cfg. Is this a new requirement that JetBrains added without adequately notifying plugin vendors ahead of time?  

If I exclude just the plantuml settings, the export of all the other settings works.

On the other hand, is there a workaround we can use so the plantuml settings can be exported?  I tried just renaming the  file to plantuml.xml in the ...options directory, but that didn't work.  

As noted above by @rhutzel, PyCharm complains about __writing__ a file, and  that the __file__ is not a directory.  However, it actually appears to have a problem __reading__ the plantuml.cfg file.

**Comment by krasa** [comment]
New version will migrate that cfg into xml.
You can try it:
https://github.com/esteinberg/plantuml4idea/releases/download/2.29.0/plantuml4idea.zip
