### ISSUE TITLE
 Possibility to allow external selection of plantuml.jar

### ISSUE THREAD

**Issue by timur-han** [esteinberg/plantuml4idea#273]
Hi,

Thank you for the contribution.

Is it possible to configure plantuml.jar to be used to render the files? Plantuml has sometimes backward compatibility issues and in such cases, I think it will help us to select the right version of plantuml.jar externally.

**Comment by krasa** [comment]
You can do it manually if you shutdown the IDE and replace e.g. `C:\Users\x\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-4\203.5981.155.plugins\plantuml4idea\lib\plantuml.1.2020.20.jar`

The problem is that the plantuml API changes quite frequently, so it will not always work.

**Comment by krasa** [comment]
I will release it after some testing, you can try it: https://github.com/esteinberg/plantuml4idea/releases/tag/3.00
