### ISSUE TITLE
Is there any plan to support plantuml new  Activity Diagram (beta)

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [esteinberg/plantuml4idea#274]
Is there any plan to support plantuml new  Activity Diagram (beta)
new  Activity Diagram (beta) like bellow
https://plantuml.com/en/activity-diagram-beta

**Comment by krasa** [comment]
fixed by https://github.com/esteinberg/plantuml4idea/issues/271

**Comment by ZhaoGuangYue1986** [comment]
> fixed by #271

ISSUE 271 most likely to support json format , is it also support new Activity Diagram (beta)?
I think json format and new Activity Diagram are different
