### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by pcr-antalya** [esteinberg/plantuml4idea#276]
Please consider adding support for File Structure?

Currently to find proper class/object I'm using search, and get lots of references is in multiple places.

**Comment by krasa** [comment]
plantuml grammar is crazy and there are too many diagram types, not feasible, unless someone makes a proper grammar for different diagrams.

**Comment by neopaf** [comment]
Eugene, I understand it you don't go deep into file right now, so you'd probably need one universal grammar.

Which grammar file format you would accept? 
Maybe I could find some time to do that.

**Comment by krasa** [comment]
Btw I am not Eugenee. :-)

People tried before and failed. https://github.com/esteinberg/plantuml4idea/blob/0d69c190155a00b25ee05f12d60956aec2c66cf2/src/org/plantuml/idea/lang/parser/PlantUml.flex
https://github.com/esteinberg/plantuml4idea/blob/0d69c190155a00b25ee05f12d60956aec2c66cf2/src/org/plantuml/idea/lang/parser/PlantUml.bnf

Compare that to my simple way:
https://github.com/esteinberg/plantuml4idea/blob/simpleGrammar2/src/org/plantuml/idea/grammar/_Puml.bnf
https://github.com/esteinberg/plantuml4idea/blob/simpleGrammar2/src/org/plantuml/idea/grammar/_PumlLexer.flex

See https://forum.plantuml.net/157/does-a-grammar-exist-for-the-language
https://github.com/esteinberg/plantuml4idea/issues/179 

You would have to create a grammar for each diagram type, and somehow differentiate them, but still, who would then maintain it?

**Comment by neopaf** [comment]
I feel I got the problem.
But maybe it is possible to ignore it?

Point of file structure, as I intend to use it  -- is to be able to quickly jump to definition of a symbol.

As I understood now, by definition you now assumed "first occurance". And that is enough for the purpose!

Maybe it is possible to make a "light" version of structure, by putting every possible word there, and allow quick-navigation to their first occurance?

Let's count buttons:
1. <shortcut> (File structure window pops up)
2. P
3. O
4. P (letters from ProductOfferingPrice)
3. Enter (accept first word that matches this mask)
4. Happy user

Currently one needs
1. goto beginning of file
2. <shortcut> (Find)
3. P
4. r
5. o
6. d
7. u
8. c
9. t
10. O
11. f
12. f
13. e
14. r
15. i
16. n
17. g
18. P
19. r
20. i
21. c
22. e
23. ESC
24. Happy user

You feel my pain, Vojtěch?

**Comment by neopaf** [comment]
Example like I use this partial-name-typing in Java context:

![Снимок экрана 2021-01-13 в 16 34 23](https://user-images.githubusercontent.com/4362564/104459010-d28f1a00-55b4-11eb-8045-dca5aeb20fab.png)

**Comment by krasa** [comment]
Actually it was super easy :)

[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/5809028/plantuml4idea.zip)

**Comment by krasa** [comment]
![image](https://user-images.githubusercontent.com/1160875/104483572-8f3ea680-55c8-11eb-81d4-bd5398738b6a.png)

**Comment by neopaf** [comment]
Precisely!

(Salivating here)

**Comment by neopaf** [comment]
AAAA. Awesome! 
Thank you very much, Vojtech.

You've save me (and, I'm sure, hundreds? thousands?) of others lots of time.

While people are looking for things, the idea they wanted to put into document may escape them (my case).
And sometimes it is hard to recover you thoughts.
But this time we could focus on what we're doing.

This is how fast it is now:
![Снимок экрана 2021-01-14 в 12 09 29](https://user-images.githubusercontent.com/4362564/104569042-7af6ba00-5659-11eb-9207-643e64aadc11.png)

**Comment by bwl21** [comment]
Just wanted to come back to this issue

Would it be possible to to do a sloppy grammar revealing only a few entities in the structure view bases on 

@startuml / enduml
class
package

Showing the first occurence of a token does not really help

**Comment by neopaf** [comment]
> Showing the first occurence of a token

Bernhard, I've checked, currently we get not the first occurrence, but definition.
Maybe you would create a separate issue with example of "otherwise"?

![Снимок экрана 2022-01-17 в 15 29 52](https://user-images.githubusercontent.com/4362564/149769944-023df9ad-e9ed-456c-8404-7130dcd8f4b1.png)

In my test: line 11 is first occurrence, but structure view says it's lower, and when I accept it, I end up on line 17, as expected:

![Снимок экрана 2022-01-17 в 15 31 58](https://user-images.githubusercontent.com/4362564/149770047-218ff463-e162-44de-8d9c-651da5fb7810.png)

(not sure why structure view says "line 16")

**Comment by bwl21** [comment]
thanks for the hint, this gives me some Idea about the usefulness of the structure view.

Navigation could be improved to

* multiple diagrams in one file
* focus on classes and attributes, but omit comments, notes etc.
* maybe in the configuration we could have a list of keywords to be considered for structure view.

As a pity I have absolutely no clue how the grammar for structure view is implemented.

maybe https://github.com/kiebor/PlantUml-Language-Service could be of some help
