### ISSUE TITLE
Jump to definition/references

### ISSUE THREAD

**Issue by pcr-antalya** [esteinberg/plantuml4idea#277]
Often want to change definition, and want to jump from a reference to an object/class/state.

Please add cross-referencing?

**Comment by krasa** [comment]
#61 ?

**Comment by neopaf** [comment]
Yeah

**Comment by krasa** [comment]
I implemented it, it does not care about syntax, just jumps between same words. Renaming also somehow works.

You can try it:
https://github.com/esteinberg/plantuml4idea/releases/tag/3.1.0-grammar

**Comment by neopaf** [comment]
Tried official upgrade, it shows 3.1.0 version now:
![Снимок экрана 2021-01-12 в 23 52 28](https://user-images.githubusercontent.com/4362564/104372934-3bcd4980-5531-11eb-92af-a71d3e17cd47.png)

I do see `map` highlighted (thanks, Eugene, this is great!), but don't seem to have cross-referencing:
![Снимок экрана 2021-01-12 в 23 53 05](https://user-images.githubusercontent.com/4362564/104372989-53a4cd80-5531-11eb-8620-700ace312099.png)

And don't seem to have refactoring:
![Снимок экрана 2021-01-12 в 23 53 31](https://user-images.githubusercontent.com/4362564/104373027-615a5300-5531-11eb-813c-772cca6f25b4.png)

Maybe something should be configured for this new magic to work?

**Comment by krasa** [comment]
It is not yet released, you have to install manually by dragging the zip into the editor
https://github.com/esteinberg/plantuml4idea/releases/tag/3.1.0-grammar2

**Comment by neopaf** [comment]
![Снимок экрана 2021-01-13 в 09 33 59](https://user-images.githubusercontent.com/4362564/104415140-84f9b980-5582-11eb-932a-cbbd292717bd.png)

Ole Ole Ole Ole!
Thanks a ton, Eugene. New era has begun!
You've saved us innumerable keystrokes and milliseconds (summed up to eras!).

**Comment by neopaf** [comment]
Small problem found:
```plantuml
@startuml
ProductOfferingPrice -- ProductUsageSpec: ForUsage >
(ProductOfferingPrice, ProductUsageSpec) .. ProductUsageSpecCharacteristic
@enduml
```

![Снимок экрана 2021-01-13 в 09 37 04](https://user-images.githubusercontent.com/4362564/104415353-ee79c800-5582-11eb-9ab3-7acf1f3ad460.png)

**Comment by krasa** [comment]
Thanks! 
Fixed, hopefully the opposite edgecase will not bother someone too much. :)

**Comment by neopaf** [comment]
Thanks! Any prerelease for lazy-me to download?

Sorry about name confusion, @krasa 
(Which is your first name? Krasa or Vojtěch?)
(In Russian krasa means beauty, wonder what it means in your language;)

**Comment by krasa** [comment]
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/5808682/plantuml4idea.zip)

No problem, first name: Vojtěch
It mean the same in Czech. :-)

**Comment by neopaf** [comment]
![Снимок экрана 2021-01-13 в 16 22 20](https://user-images.githubusercontent.com/4362564/104457773-226ce180-55b3-11eb-89c8-278148e08704.png)

**Comment by krasa** [comment]
new build with a little better highlighting of keywords
https://github.com/esteinberg/plantuml4idea/releases/download/3.1.0-grammar3/plantuml4idea.zip

**Comment by neopaf** [comment]
nothing broken as far as I see.

**Comment by krasa** [comment]
Thanks a lot!

**Comment by bwl21** [comment]
> new build with a little better highlighting of keywords and structure view :)
> https://github.com/esteinberg/plantuml4idea/releases/download/3.1.0-grammar3/plantuml4idea.zip

I don't know how to handle the structure view. It looks like this but not reflect the sructure


![image](https://user-images.githubusercontent.com/2022976/105508605-da457180-5ccc-11eb-9fcc-62c8a0c411f5.png)

**Comment by krasa** [comment]
It just shows the first occurence, not structure. https://github.com/esteinberg/plantuml4idea/issues/276
