### ISSUE TITLE
V1.2020.26 fix

### ISSUE THREAD

**Issue by DonMathi** [esteinberg/plantuml4idea#281]
Please

Are you sometime in the near future able to make an update for V1.2020.26?
https://plantuml.com/changes

Best Regards
Kjeld

**Comment by krasa** [comment]
Bundled here, I will release it after some testing, you can try it: https://github.com/esteinberg/plantuml4idea/releases/tag/3.00

**Comment by DonMathi** [comment]
Thank you very much. Works like a charm
Best Regards
Kjeld
