### ISSUE TITLE
How to remove ad.

### ISSUE THREAD

**Issue by sessionbean** [esteinberg/plantuml4idea#282]

**Comment by krasa** [comment]
ad?

**Comment by sessionbean** [comment]
yes, when we have syntax error.

**Comment by krasa** [comment]
https://github.com/plantuml/plantuml/blob/56cd2269dd6b95925e8a8c44102002d5749549bc/src/net/sourceforge/plantuml/error/PSystemError.java#L234-L249

**Comment by krasa** [comment]
https://plantuml.com/professional

**Comment by sessionbean** [comment]
thank,good to know
