### ISSUE TITLE
After update to 3.3.0 don`t work inspections for spelling

### ISSUE THREAD

**Issue by VadimShtukan** [esteinberg/plantuml4idea#284]
After update to 3.3.0 don`t work inspections for spelling and code analysing.
Inspect code has result "No suspicious code found. 1 files processed in 'File ....puml"

**Comment by krasa** [comment]
Thanks! You can update.

**Comment by VadimShtukan** [comment]
It works now only for English grammar. For Russian spelling still doesn't work. For another files it works perfect. 
I use Grazie.

**Comment by krasa** [comment]
I will try to add Grazie later.

**Comment by krasa** [comment]
You can try it, not sure how well it will work, it may need to some way to distinguish what is a part of the sentence and what is a separator from another sentence/entity - which is currently all special characters, unless in braces...
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/5842427/plantuml4idea.zip)

**Comment by VadimShtukan** [comment]
In version 3.5.0 it still doesn't work. I noticed that if write text between [ ] it works correctly. For example [Оалвыалвы]

**Comment by krasa** [comment]
Now it should work, and also the code navigation
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/5849368/plantuml4idea.zip)

**Comment by VadimShtukan** [comment]
Now it's working perfectly! Thanks!
