### ISSUE TITLE
Feature request: Relative paths and output file naming

### ISSUE THREAD

**Issue by adrianrudnik** [esteinberg/plantuml4idea#285]
Using goland right now, I'm trying to find a way to save a file with a given filename and path.

```
@startuml <test.svg>
@startuml test.svg
@startuml ./test.svg
```

seems to have no effect, the `demo.puml` is always named `demo.png` in the "Save current diagram only" dialog. It is also placed into the root of the project, not in the same folder where the puml-file is located.

Am I missing something or would this be possible to implement?

Edit: It would also be nice to have svg as configurable default.

**Comment by krasa** [comment]
Sorry, I broke it in the last version.
`@startuml test` should work, for some reason `@startuml test.svg` does not return the extension from PlantUML API. I would have to parse it manually.... 
Default folder changed. 
File type settings added.
