### ISSUE TITLE
False Warning 'Non-ASCII characters in an identifier'

### ISSUE THREAD

**Issue by msilber** [esteinberg/plantuml4idea#288]
Despite the character set being set to UTF-8 in the preferences, when using non-ASCII characters in PlantUML diagrams (for instance when creating diagrams in languages other than English), the warning

> Non-ASCII characters in an identifier

is shown on the Problems tab. In a large diagram, this can lead to a considerable amount of warnings, leading to an actually important warning being overlooked.

What's more: the warning is not correct in that the non-ASCII character is not used in an identifier, but in what is the equivalent of a string literal (i.e., text opaque to the renderer).

**Comment by krasa** [comment]
Try this: 
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/5951721/plantuml4idea.zip)
