### ISSUE TITLE
Export diagram user experience regression

### ISSUE THREAD

**Issue by bondden** [esteinberg/plantuml4idea#289]
# Steps to reproduce:

## Previously (not sure till which version):

filename: `some.file.name.puml`
title: ANY TITLE
exported: `some_file_name.png`

It's ok, cause provides unique name without whitespaces, ideal for usage in any documentation, including web.

## In 4.2:

filename: `some.file.name.puml`
title: ANY TITLE

If `Use page titles in exported file names` is on:
exported: `diagram.png`
else if `Use page titles in exported file names` is on:
exported: `diagram-ANY TITLE.png`

# Expected:

filename: `some.file.name.puml`
title: ANY TITLE

If `Use page titles in exported file names` is on:
exported: `some_file_name.png`
else if `Use page titles in exported file names` is on:
exported: `some_file_name-ANY TITLE.png`

**Comment by krasa** [comment]
Is it ok if the default filename will be `some.file.name.png` instead of `some_file_name.png`?
You can try it:
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/5965905/plantuml4idea.zip)

**Comment by bondden** [comment]
It is really ok! Even more expected, cause uses an original name. The update works correctly with the both options of `Use page titles in exported file name`. Thank you!

**Comment by krasa** [comment]
Thank you!
