### ISSUE TITLE
Change PlantUML Server link

### ISSUE THREAD

**Issue by thoism** [esteinberg/plantuml4idea#290]
Hi all,

The plugin is just fantastic!

Is it possible to:

1. Change the default PlantUML Server URL? We have a PlantUML Server instance running inside our network.
2. Add the option to copy directly the SVG/PNG link [very useful for JIRA/GitLab inline images] using the configured PlantUML Server link

**Comment by krasa** [comment]
Is it just the matter of the prefix?

**Comment by krasa** [comment]
Fixed in 4.5.1

**Comment by thoism** [comment]
> Is it just the matter of the prefix?

@krasa I only saw the notification just now. Apologies for not replying earlier. Basically yeah that was the idea!

Thank you for tackling this!

**Comment by thoism** [comment]
I tested it and I noticed that it requires a /plantuml/ context in the URL. I think this should not be the case since our internal server for example is:

`plantuml.company.com` and not `plantuml.company.com/plantuml/`

Thank you

**Comment by krasa** [comment]
Are you sure? PlantUML server has /plantuml/ hardcoded https://github.com/plantuml/plantuml/blob/2404fb605b6749af11e5d666860fa39a7f7b4547/src/net/sourceforge/plantuml/picoweb/PicoWebServer.java#L105

**Comment by thoism** [comment]
The thing is that it is behind a reverse proxy so I guess our IT mapped it how he wanted. If you believe it is not worth changing it, I am OK with it; but I think flexibility in this case would not harm anyone.

**Comment by krasa** [comment]
try it now

**Comment by thoism** [comment]
thanks man! awesome!
