### ISSUE TITLE
Doesn't work in markdown

### ISSUE THREAD

**Issue by danielzgtg** [esteinberg/plantuml4idea#292]
This appears to be a regression since #256. I can't get PlantUML rendering inside Markdown.

`.puml` files work though. I'm using 4.3.1 on IntelliJ Ultimate 2020.3.

# The file:

    # Hello World
    
    ```plantuml
    Object <|-- ArrayList
    
    Object : equals()
    ArrayList : Object[] elementData
    ArrayList : size()
    ```

# Actual behaviour

![image](https://user-images.githubusercontent.com/25646384/108814458-d2edde00-7580-11eb-90b1-210110235115.png)

# Expected behaviour

I should see code highlighting on the left and a rendered output on the right

**Comment by krasa** [comment]
This plugin does not handle Markdown preview rendering. 
But there was a small bug, so it will be rendered at least in the PlantUml tool window.
