### ISSUE TITLE
UnsupportedOperationException with Pseudo sprite example from plantuml documentation

### ISSUE THREAD

**Issue by chrisbu** [esteinberg/plantuml4idea#296]
This "Pseudo sprite" example from plantuml documentation causes `java.lang.UnsupportedOperationException`

Documentation: https://plantuml.com/salt  (in the "Pseudo sprite" section)
Example from the documentation below:

```
@startsalt
{
 [X] checkbox|[] checkbox
 () radio | (X) radio
 This is a text|[This is my button]|This is another text
 "A field"|"Another long Field"|[A button]
 <<folder
 ............
 .XXXXX......
 .X...X......
 .XXXXXXXXXX.
 .X........X.
 .X........X.
 .X........X.
 .X........X.
 .XXXXXXXXXX.
 ............
 >>|<color:blue>other folder|<<folder>>
^Droplist^
}
@endsalt
```

Specifically, it's the `<<folder` .. `<<folder>>` that's causing the issue.  Remove that and it's fine.

**Comment by krasa** [comment]
It does not work for SVG, you can switch to PNG preview.

http://www.plantuml.com/plantuml/svg/bP1DQiKW483tSueXgzTD3r22l43f2Re8o7jWeccarYawWPJQkpUf-KcM_H2Spnbrz1fP1OxACNm3olg6RM_QzuR69FSOyFA0GMbBcF1IBp7WQsyZJaCXcv6JNFtZ2vk1cVmjRIMUk3VXhn2mgB2pnkaY5TMISEJVy2KlochT3rYM7Jbj0k3ZWSdgcTscwM0RERVmFpkVShvTY5Isv2WyDMum8ZyXDvhMZeM0-tEWJsSZt-47hiRh-QT_0G00

**Comment by krasa** [comment]
Fixed
