### ISSUE TITLE
New file export dialog should remember the previous directory

### ISSUE THREAD

**Issue by uhafner** [esteinberg/plantuml4idea#297]
Thanks for adding a configuration of the default file extension in the latest version of the plugin. This new feature introduced a usability regression: before that change the dialog remembered its last directory. Now the dialog starts always from the current directory. It would be helpful if the dialog would remember that last export directory.

Steps to reproduce:
1. Open export dialog: Current directory is the same directory that contains the diagram
2. Change directory
3. Save: Diagram is saved in new directory
4. Open export dialog: Current directory is the same directory that contains the diagram

Expected behavior:
In last step 4. I would expect that the dialog shows the previous export directory that has been used in step 2.

**Comment by krasa** [comment]
Hmm I was afraid someone will not like it. I will have to add configuration for this too.

**Comment by krasa** [comment]
You can try it, it is disabled by default: [plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/6131857/plantuml4idea.zip)

**Comment by uhafner** [comment]
Thanks for the quick fix! It works like a charm 🎉
