### ISSUE TITLE
PyCharm integration: support TODO comments

### ISSUE THREAD

**Issue by moritz-ritter** [esteinberg/plantuml4idea#298]
PyCharm has a nice TODO comments overview for projects (and there is a nice plug-in for PlantUML).

Unfortunately, TODO comments in PlantUML *.puml files do not get listed in the overview. I checked with PyCharm support (case https://intellij-support.jetbrains.com/hc/en-us/requests/3181195) and they say, that the PlantUML plug-in is likely not supporting the detection of TODO comments. I don't know what that means, but it would be nice to have that.

**Comment by krasa** [comment]
It says 404 OOPS The page you were looking for doesn't exist. But I probably know what to do.

**Comment by moritz-ritter** [comment]
I printed it to a PDF and attached below.
[Jetbrains_3181195_20210315.pdf](https://github.com/esteinberg/plantuml4idea/files/6141918/Jetbrains_3181195_20210315.pdf)
