### ISSUE TITLE
Make Position and Layout of Preview Panel configurable

### ISSUE THREAD

**Issue by koll051** [esteinberg/plantuml4idea#299]
The position of the preview panel currently is fixed to the right side of the editor. 

This isn't optimal if you work with tool windows on the right (as I happen to do):
![grafik](https://user-images.githubusercontent.com/31656637/111331878-9be78580-8671-11eb-8c2d-adb18c33baee.png)

nor with split editors:
![grafik](https://user-images.githubusercontent.com/31656637/111333147-b0784d80-8672-11eb-89fa-7a4bb7f63629.png)

It would be great if position and layout of the preview panel could be made configurable.

The [IntelliJ AsciiDoc Plugin](https://intellij-asciidoc-plugin.ahus1.de/) provides this feature. It has these layout options:
![grafik](https://user-images.githubusercontent.com/31656637/111334482-e4a03e00-8673-11eb-9543-e1a7ccc64904.png)
Switching from vertically to horizontally changes the last 2 options:
![grafik](https://user-images.githubusercontent.com/31656637/111334046-86735b00-8673-11eb-9541-ba3d8612acd2.png)

Such configuration would support the scenarios above much better:

![grafik](https://user-images.githubusercontent.com/31656637/111335381-a22b3100-8674-11eb-9602-65575ca0a9b5.png)
(split vertically, editor on right side)

![grafik](https://user-images.githubusercontent.com/31656637/111336291-66dd3200-8675-11eb-837c-a6995e9984f4.png)
(split editors; editor 2 split horizontally, editor in lower half)

The [IntelliJ AsciiDoc Plugin is under the Apache License](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/LICENSE), so [their implementation](https://github.com/asciidoctor/asciidoctor-intellij-plugin) could possibly be reused.

Thank you a lot for your consideration!

**Comment by krasa** [comment]
You can try a prototype: 
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/6253587/plantuml4idea.zip)

**Comment by krasa** [comment]
All good?
