### ISSUE TITLE
Support multiple PlantUML sources per file

### ISSUE THREAD

**Issue by esteinberg** [esteinberg/plantuml4idea#3]
Add support for multiple PlantUML sources per text file

**Comment by bwl21** [comment]
Even if it is an old issue 

> Additional SaveAll button will save all diagrams in file with ordering number

did you implement this? I cannot find that button.

**Comment by krasa** [comment]
It saves all pages. 
![image](https://user-images.githubusercontent.com/1160875/144902402-76849256-34b5-4915-9a00-64189c2c2a6c.png)

**Comment by bwl21** [comment]
The button looks different on my site and is even greyed out

![image](https://user-images.githubusercontent.com/2022976/144903964-0deb3376-30c2-484b-994d-292acef83cd0.png)

**Comment by bwl21** [comment]
my file holds @startjson commands, maybe the PlantUML integration does not recognize this:

**Comment by krasa** [comment]
@startjson should work fine, does the plugin render previews?

**Comment by bwl21** [comment]
yes it does.

**Comment by krasa** [comment]
You can update
