### ISSUE TITLE
Preview engine in Clion treats shorthand activation syntax as an error

### ISSUE THREAD

**Issue by donato-iot** [esteinberg/plantuml4idea#306]
The following two activation methods are valid and render correctly using the standard plantuml docker container to render; however I get a syntax error in Clion for the shorthand +/- syntax.

@startuml
'https://plantuml.com/sequence-diagram

autonumber
Alice -> Bob: Authentication Request
activate Bob
Bob --> Alice: Authentication Response
deactivate Bob

Alice -> Bob+: Another authentication Request
Alice <-- Bob-: another authentication Response
@enduml

**Comment by krasa** [comment]
http://www.plantuml.com/plantuml/uml/RS_12i8m3CRnUvuYDmzITnyYcu_W6sHTS8KrdKtgyzig28CTUYd_7nyPr2XRYIkS5hDD-wxRLfBsS_4fTiglmkBPpO6UcI805KjIuiGPnZLuHdV3Uvfw78ijB1OyMKY2ZoRLWBo5Dnct2Ef3Ly5N7X3TaYZ3p3kr6pfN9gcwZ7Iy-AklphNSzKZ7-NzjO9dhlHy0

**Comment by donato-iot** [comment]
My apologies.  The documented shorthand syntax uses ++ and -- .  Odd that the dockerized version I use is tolerant of single + and -.

**Comment by krasa** [comment]
maybe older version?
