### ISSUE TITLE
`plantuml.include.path` by default don't include baseDir

### ISSUE THREAD

**Issue by dpblh** [esteinberg/plantuml4idea#307]
> Additional 'plantuml.include.path'
> - the current folder is automatically included

Without specifying any parameters, I expect the current folder to be included in 'plantuml.include.path', but the folder won't include.

![image](https://user-images.githubusercontent.com/8198859/119120640-2f07b780-ba35-11eb-886b-8ceb6ae212c6.png)

![image](https://user-images.githubusercontent.com/8198859/119120588-22835f00-ba35-11eb-92a1-ab64473c9c94.png)

![image](https://user-images.githubusercontent.com/8198859/119120693-3b8c1000-ba35-11eb-9a7f-837638116370.png)

MacOs Big Sur
IDEA Ultimate 2020.3
Plugin 5.3.0

**Comment by krasa** [comment]
and where is your file located?

**Comment by dpblh** [comment]
deep in the project `src/pages/master/c1.puml`

**Comment by krasa** [comment]
the current folder is the one c1.puml is located in.

**Comment by dpblh** [comment]
I am so sorry!
For some reason I thought that the current folder is the root folder of the project.
I thought the root folder is included in the search paths.

**Comment by krasa** [comment]
Well, it could be, but it would not work in any other IDE, so perhaps it is better this way.
