### ISSUE TITLE
Add Theme Support

### ISSUE THREAD

**Issue by monksy** [esteinberg/plantuml4idea#308]
Currently the plugin considers a theme command to be invalid. 

Feature request: Add theme support, or ignore it for the time being.

Theme doc: https://plantuml.com/theme

**Comment by krasa** [comment]
you can download and use a new plantuml jar until it is bundled.

**Comment by monksy** [comment]
I had no idea it was that recent.

**Comment by monksy** [comment]
Created the pr with the update: https://github.com/esteinberg/plantuml4idea/pull/309

I couldn't find any references to the old name that would prevent this from working.

**Comment by tstorek** [comment]
Hello,

is anywhere documented how I can set the path to my own plantuml.jar?

**Comment by krasa** [comment]
![image](https://user-images.githubusercontent.com/1160875/119961945-de4d0d00-bfa6-11eb-94b0-075d337a0a91.png)
