### ISSUE TITLE
PlantUmlFileType and PlantIUmlFileType both have the same .getDisplayName()

### ISSUE THREAD

**Issue by ahus1** [esteinberg/plantuml4idea#310]
On IntelliJ 2021.2 EAP with plugin version 5.3.0 I receive the following error:

```
java.lang.Throwable: 
org.plantuml.idea.lang.PlantUmlFileType@58020cad from 'PluginDescriptor(name=IDEA CORE, id=com.intellij, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-1\212.3116.43\lib, version=212.3116.43, package=null)' (class org.plantuml.idea.lang.PlantUmlFileType) and
org.plantuml.idea.lang.PlantIUmlFileType@433425ff from 'PluginDescriptor(name=IDEA CORE, id=com.intellij, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-1\212.3116.43\lib, version=212.3116.43, package=null)' (class org.plantuml.idea.lang.PlantIUmlFileType)
 both have the same .getDisplayName(): 'PUML'. Please override either one's getDisplayName() to something unique.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.checkUnique(FileTypeManagerImpl.java:1310)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.checkFileTypeNamesUniqueness(FileTypeManagerImpl.java:1293)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.registerFileTypeWithoutNotification(FileTypeManagerImpl.java:1256)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:333)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:222)

```

IDE details: 

IntelliJ IDEA 2021.2 EAP (Ultimate Edition)
Build #IU-212.3116.43, built on May 27, 2021
IntelliJ IDEA EAP User
Expiration date: June 26, 2021
Runtime version: 11.0.11+9-b1460.1 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Non-Bundled Plugins: PsiViewer (212-SNAPSHOT), com.github.camork.fileExpander (1.6), org.intellij.plugins.postcss (212.3116.29), org.jetbrains.plugins.slim (212.3116.29), com.intellij.javafx (1.0.3), com.jetbrains.ChooseRuntime (1.2), de.docs_as_co.intellij.plugin.diagramsnet (0.1.7), org.toml.lang (0.2.147.3871-211), CheckStyle-IDEA (5.52.0), YourKit Java Profiler 2020.7-b376 Integration (2020.7.376.0), org.jetbrains.idea.grammar (2021.1.1), com.intellij.tailwindcss (212.3116.29), com.dmarcotte.handlebars (212.3116.29), org.jetbrains.plugins.vue (212.3116.29), org.jetbrains.plugins.ruby (212.3116.29), PlantUML integration (5.3.0), org.mapstruct.intellij (1.2.4), org.asciidoctor.intellij.asciidoc (0.32.50), org.asciidoctor.intellij.asciidoclet (0.1.2)
Kotlin: 212-1.4.32-release-IJ3116.43

**Comment by krasa** [comment]
Thanks! Should be fine now.

**Comment by ahus1** [comment]
Thanks - don't see that error with plugin version 5.4.0 - thank you for the quick fix and deployment of a new version!
