### ISSUE TITLE
Terrible performance while typing #2

### ISSUE THREAD

**Issue by cheshir** [esteinberg/plantuml4idea#311]
OS: MacOS Big Sur 11.0.1
IDE: Jetbrains Goland 2021.1
Plugin version: latest
PlantUML version: 1.2021.7

Looks like diagram is rendered in the same process where typing handled. Delay for typing is similar to rendering time provided by plugin.

**Comment by krasa** [comment]
Works fine for me, could you provide a CPU snapshot?
https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems
(Help | Diagnostic | Start CPU Usage Profiling.)

**Comment by cheshir** [comment]
@krasa CPU profile: https://we.tl/t-wDnklC2DkF

**Comment by krasa** [comment]
Thanks. I moved things to the background, which should act as a workaround. But typing was not supposed to trigger this in the first place, something strange is happening.

Debug logging would help.
![image](https://user-images.githubusercontent.com/1160875/121059620-f5b7a180-c7c1-11eb-9bdd-3ce2ebce1f55.png)
Add this:  ```#org.plantuml```
Then post idea.log or part of it, there might be something private...

You can try the fixed version:
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/6610795/plantuml4idea.zip)

**Comment by krasa** [comment]
I reproduced the problem when the file is opened multiple times or the toolwindow is also opened, this fix should be good enough for it.
Is there something specific in your case? Some custom settings?

**Comment by krasa** [comment]
I fixed it a little more, no need for the log anymore.

**Comment by krasa** [comment]
[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/6617992/plantuml4idea.zip)

**Comment by krasa** [comment]
the fix was released

**Comment by cheshir** [comment]
@krasa Thanks a lot! You're awesome.
