### ISSUE TITLE
Saved diagram scaled 2x

### ISSUE THREAD

**Issue by vsigler** [esteinberg/plantuml4idea#316]
Hello,

when I saved the created diagram and displayed it separately, I found out that it is actually twice the size than displayed in Idea. It is the same no matter if I use PNG or SVG as output. I am running on MacOS, so it might be somehow related to the UI scaling. I can also see it at this size if I include the generated image in a markdown, but the standalone puml file displays in the correct scale.

I was able to workaround it by adding 0.5 scale to plantuml config.
```
scale 0.5
```

However, I still think it might be useful to check, where the plugin gets the actual amount of pixels to generate.

**Comment by krasa** [comment]
If you have OS scaling or Retina, then the generated image will have more pixels, but it should be the same size when viewing the exported image in a scaled app as in IntelliJ. 
It will appear 2x bigger in an unscaled app. 
If the generated image was not scaled, then it would appear blurry in scaled apps. 
I tested it on Win 10.

**Comment by vsigler** [comment]
That is the thing, if you embed it in a markdown or HTML, the scaling information gets lost. It might be good to add an option which resolution/scale to use for export - the render resolution (2x) or display resolution (1x). You would only get blurriness when using a fractional scale and using PNG. When using SVG, there is no blurriness  no matter what resolution you use.

**Comment by krasa** [comment]
yes, an option could be done.
