### ISSUE TITLE
PlantUML v1.2021.9 bump

### ISSUE THREAD

**Issue by 0n3d3r3r** [esteinberg/plantuml4idea#318]
Hi!
Congrats for the great work. This plugin is really cool.
Are you planning to release soon a plugin upgrade bumping the PlantUML library to v1.2021.9 released on July 25?
For some people working behind a proxy the plugin is also the simplest/quickest way to get access to the latest PlantUML jar.
Thanks.

**Comment by krasa** [comment]
done
