### ISSUE TITLE
EmptySvgException when write docs over two lines

### ISSUE THREAD

**Issue by mactkg** [esteinberg/plantuml4idea#319]
I encountered a strange issue. I tried to find a workaround, but I give up... Please help!

# Environment
I'm using this plugin on WebStorm 2021.2/MacBook Air(M1, 2020).
Graphviz is installed using homebrew.

# The error
I wrote a small test doc but I got an error like this.

```puml
@startuml
interface List
interface Collection
@enduml
```

![error](https://user-images.githubusercontent.com/178418/129429738-eacaddf7-743d-4b9d-876c-49b6a7119649.png)

# Fixed case
The error is fixed when commenting out a line.

```puml
@startuml
interface List
- interface Collection
@enduml
```

![ok](https://user-images.githubusercontent.com/178418/129429763-939b5284-5a96-453b-a983-e525472119e7.png)

# Try custom PlantUML jar but failed
I installed PlantUML via homebrew, and I changed the plugin configuration to use a custom jar but got the same result.

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/178418/129429858-beaa83e6-5013-4f8f-8c06-9cc08b66a29c.png">

# Try using the custom jar from CLI, it works
However, I use the same jar from CLI, it works...

`java -jar /opt/homebrew/Cellar/plantuml/1.2021.9/libexec/plantuml.jar -Djava.awt.headless=true FILENAME`

![data](https://user-images.githubusercontent.com/178418/129429887-9eec220e-2559-4275-a6c9-8048b5810777.png)

Is there any other way to fix it?

**Comment by krasa** [comment]
Strange, it works fine for me on Win10.

Disable this 
![image](https://user-images.githubusercontent.com/1160875/129438119-d4d1fd93-b687-4720-815c-a23a98a2764d.png)

**Comment by mactkg** [comment]
@krasa 
Thanks for the reply! I disabled it but got the same error.

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/178418/129442721-6bc77db3-909a-4dc5-9e1e-25ca58b26f6d.png">

I try Remote Rendering, it works.

**Comment by krasa** [comment]
It seems that your graphviz does not work correctly, perhaps try a different version

**Comment by mactkg** [comment]
OK, I try graphviz 2.44 as mentiond https://plantuml.com/ja/graphviz-dot

**Comment by mactkg** [comment]
I notice that installing `graphviz` / `plantuml` was failed somehow.  The plugin works correctly after reinstalling xcode command line tools by `sudo rm -rf /Library/Developer/CommandLineTools && xcode-install --install` and `graphviz` and `plantuml` by `brew reinstall plantuml, graphviz`.

Thanks.
