### ISSUE TITLE
Plugin 'PlantUML Studio' is broken with Jetbrains series 212 baselines: CLion CL-212.*, Pycharm PY-212.*, etc

### ISSUE THREAD

**Issue by infojg9** [esteinberg/plantuml4idea#321]
Dear Plantuml4idea Team,

firstly thank you for your very efficient and useful plugin solution.

It looks like after recent Jetbrains Jetbrains series 212 baselines updates, it is broken again:

1. Plugin 'PlantUML Studio' (version '2021.1.1') is not compatible with the current version of the IDE, because it requires to build 211.* or older but the current build is CL-212.5080.54

2. Plugin 'PlantUML Studio' (version '2021.1.1') is not compatible with the current version of the IDE, because it requires to build 211.* or older but the current build is PY-212.5080.64

3. etc

Any hint would be very highly appreciated, thank you.

Best Regards
infojg9

**Comment by krasa** [comment]
PlantUML Studio is a different plugin.
