### ISSUE TITLE
ngdiag: plugin creates an unexpected diagram

### ISSUE THREAD

**Issue by QuaritschGerFfm** [esteinberg/plantuml4idea#325]
Hi,
I am new in using PlantUML, but when I use the following plantUML Code, the IntelliJ Plugin is generating another diagram than the website: [http://www.plantuml.com](http://www.plantuml.com/plantuml/uml/)

```
@startuml
!include <office/Servers/application_server>
!include <office/Servers/database_server>
!include <logos/kubernetes>
!include <logos/prometheus>
skinparam monochrome true
skinparam BackgroundColor transparent
nwdiag {
  network net_1 {
    comp01 [description = "<$application_server> <$kubernetes> <$prometheus>\n Kubernetes Prometheus\n (federation scraper)"];
    routerFfm;
  }

  routerFfm -- inet;
  inet [shape = cloud];
  inet -- routerMuc;
  network net_2 {
    routerMuc;
    comp02 [description = "<$application_server> <$kubernetes> <$prometheus>\n Kubernetes Prometheus \n (federation endpoint)"];
  }
}
@enduml
```

This is what I get from the plugin:
![grafik](https://user-images.githubusercontent.com/35000927/137785604-bf888302-80df-4e61-9e0f-04aa9060164e.png)

And I received that from the online generator and I expected that too:
![grafik](https://user-images.githubusercontent.com/35000927/137785837-d9bf3888-41a1-4843-904a-3188e29a7148.png)

Link: [Online generator](//www.plantuml.com/plantuml/png/jP91Qp8n48Rl-HNpYOUl1x5wrHPfePTIAFHeHM8ogs4tCs6Ir4FnlpUxbMMnzjXJoFkysPa7TXMJbfHze_uvCass24kkAcTm-eRoWHAdEeJ66PqSqpPssVtlPQkJtkc8LveDxpbEwxn38KmOVx8Wx34TC1SMQqT1Y_RWcTWSMWH9CWx8WpRrNZYJVUI6fM1DiI2afEXedTx3fm8WJ4UMkZstiou1CEp3xGpM5gCH5revk8FHSdp55fRZmTRbDjZpdU2vP_3QWvB_hz2YT5-2CaG7b9lHPj6D5yu9vQdoxVMar221oGGSOIgaEs4T3-LjsSuqdEscpqll-z5BDeiBpVbPSr3ehUT_PmqNsaWsiADqzZwfargLhFtTlW00)

Would be nice if that would be fixed in the future.
Otherwise, many thanks for the great plugin!

**Comment by krasa** [comment]
Yes, it is bundled and configurable, and you are using a super old plugin version.
