### ISSUE TITLE
Cannot find Graphviz error after "brew install graphviz" on M1 mac

### ISSUE THREAD

**Issue by doljae** [esteinberg/plantuml4idea#330]
## Description
<img src="https://user-images.githubusercontent.com/37795866/139628680-d7679353-938f-4253-9e53-e9d0abe09282.png" width=50% height=50%>

- I installed graphviz through homebrew and tried to use it through a plugin in intellij on M1 mac.
- However, I have confirmed that this error occurs in some diagrams. (This case is a state machine diagram)

![image](https://user-images.githubusercontent.com/37795866/139628913-5bd2ba63-efa1-4b87-b4f0-f6c183ac401a.png)

- And I confirmed that the dot directory is different from the default setting.(default is `/usr/local/bin/dot`)
- there's no dot file in `/usr/local/bin` directory. I think this is a reason.

~~So I copied the dot file in `/opt/homebrew/bin/` to `/usr/local/bin`. But I am still getting the same error.
Is there any way to use normally?~~

## Update
After moving the dot-related files to `/usr/local/bin`, I restarted intellij and confirmed that it works normally.

I think the problem is because this plugin looks at the dot file inside the directory of `/usr/local/bin`.
If there is a way to modify the path of the dot file through intellj or changing settings, please share.

**Comment by krasa** [comment]
Default paths are handled by plantuml itself: https://github.com/plantuml/plantuml/blob/b27fa50b5038140eba66e0c82eaed0d0403ed517/src/net/sourceforge/plantuml/cucadiagram/dot/GraphvizLinux.java#L49

You can set a custom path at settings:
![image](https://user-images.githubusercontent.com/1160875/145806346-c8755d5c-4bb3-4c65-a8e5-85d7b057d732.png)

**Comment by doljae** [comment]
Thanks.
Actually, I already found the custom setting in IntelliJ preference... Anyway thank you for kind reply :)
