### ISSUE TITLE
"Graphviz is now included in PlantUML" but plugin does not work without system-installed graphviz

### ISSUE THREAD

**Issue by fdcds** [esteinberg/plantuml4idea#332]
I do not have graphviz installed on my system and trying to render:
```plantuml
@startuml
testdot
@enduml
```
results in `Error: File does not exist`.

However, on the about page of the PlantUML plugin, it says "Graphviz is now included in PlantUML".

How do I make use of the included Graphviz?

**Comment by krasa** [comment]
Do you mean the result is this? 
![image](https://user-images.githubusercontent.com/1160875/140337625-dbee069f-8a12-4e39-94a9-027181cef39c.png)


Does your config look like this?
![image](https://user-images.githubusercontent.com/1160875/140337911-5aaada2f-b5da-404f-92cc-6326787f8293.png)

**Comment by fdcds** [comment]
Yes to both questions.

**Comment by krasa** [comment]
please try it from a command line.

**Comment by fdcds** [comment]
I assume you mean GoLand's built-in terminal?

```
sh-5.1$ dot
sh: dot: command not found
```

Which path is the included `dot` binary under? Can I manually enter the path of the included version of Graphviz in the config?

**Comment by krasa** [comment]
Your OS's terminal would be better:

`java -jar plantuml.jar diagram.txt`
 - https://plantuml.com/download

**Comment by krasa** [comment]
IIt seems that Graphiz is embedded only for Windows.

**Comment by krasa** [comment]
https://plantuml.com/graphviz-dot

**Comment by fdcds** [comment]
Thanks for the hint! `!pragma layout smetana` works fine in my case.
