### ISSUE TITLE
How to disable automatic split screen rendering?

### ISSUE THREAD

**Issue by TwoFistedJustice** [esteinberg/plantuml4idea#335]
Is there a way to disable the automatic split screen rendering in the main window of my IDE? (see screenshot)

This feature frequently gets in my way. It pops up and covers or squishes a window I need to see. And while I can turn it "off" temporarily by clicking the minus or gear icons, it pops right back up as soon as I click into my UML code.

Jetbrains already has buttons for split screen rendering, but this thing operates completely independently of those.

How do I make it go away?

``
![Plant_UML_Screenshot](https://user-images.githubusercontent.com/22874887/141525122-238cab1a-09cf-4aa8-ab4b-2874c8ada5f8.png)

**Comment by krasa** [comment]
![image](https://user-images.githubusercontent.com/1160875/141528924-b969519d-a270-4751-8e3e-375fa4e41134.png)
