### ISSUE TITLE
PlantUML 5.9.0 Failed to save images

### ISSUE THREAD

**Issue by xiaochenge** [esteinberg/plantuml4idea#342]
![image](https://user-images.githubusercontent.com/30567519/146870533-3e588ed1-86de-420f-9487-c34f5084b1c6.png)

**Comment by krasa** [comment]
thanks, you can update

**Comment by xiaochenge** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
