### ISSUE TITLE
Render UML in comment block

### ISSUE THREAD

**Issue by tom10271** [esteinberg/plantuml4idea#345]
Go to https://plantuml.com/eclipse and search `If you write some comment in PlantUML language, the corresponding diagram is automatically displayed. And if you have several comments with diagrams, it selects the one the cursor is in.`

https://plantuml.com/img/eclipse105.png

Can we support this?

**Comment by krasa** [comment]
We already support it, open a tool window panel.

**Comment by tom10271** [comment]
ok because I tried in python comment block and it is not working

**Comment by krasa** [comment]
please post an example

**Comment by tom10271** [comment]
I have uninstalled it minutes ago as the autocomplete is not supporting well. We can close this issue if you wanted.
