### ISSUE TITLE
Intellisense is not working

### ISSUE THREAD

**Issue by valentine-palazkov** [esteinberg/plantuml4idea#346]
JetBrains Rider IDE.

I remember that something one year ago I had intellisense working with no probs.

I have not used it for a while.

But 7 months ago I needed to create an UML diagram and now it looks like this:

![image](https://user-images.githubusercontent.com/649010/153704114-c3cc8be6-0ba8-47ce-8637-c57030c1c4ba.png)

No intellisense at all.

It's still usable but it could be better.

My IDE version is like this:

![image](https://user-images.githubusercontent.com/649010/153704147-1a1ddd1e-b459-4b08-a391-a0b2c9bc75f1.png)

**Comment by krasa** [comment]
Make sure the extension is registered
![image](https://user-images.githubusercontent.com/1160875/153704223-f78aff14-52f7-4f4b-9811-bb26d370a967.png)

**Comment by krasa** [comment]
The plugin is by default registered to *.puml, there is normally no need for this config.

**Comment by valentine-palazkov** [comment]
@krasa 

have no idea how it happened on my PC, but I did nothing to get only *.plantuml in my list, sorry
