### ISSUE TITLE
Toolwindow for plugin is not necessary while already support preview

### ISSUE THREAD

**Issue by gerryhjs** [esteinberg/plantuml4idea#347]
![image](https://user-images.githubusercontent.com/45413498/158946364-c883655b-4ac2-459e-906b-b341524b8ec7.png)
See the screenshot.

**Comment by gerryhjs** [comment]
Maybe you can remove the toolwindow.

**Comment by krasa** [comment]
It is necessary for non-puml files - embedded comments in java files, etc.
