### ISSUE TITLE
Bump PlantUML to 1.2022.2

### ISSUE THREAD

**Issue by kriegaex** [esteinberg/plantuml4idea#348]
Due to https://github.com/plantuml/plantuml/issues/969, I need to use `skin rose` after bumping my Maven plugin to 1.2022.2, otherwise the colouring changes from coloured to grey-scale. The problem is that the IDEA plugin does not find that skin, so it displays an error when I want to view my diagram from within IDEA. From Maven, it works, but this plugin embeds PlantUML 1.2022.1.

Looking forward to the next release. Keep up the great work! 🙂

**Comment by krasa** [comment]
You can always use a custom PlantUML jar at moments like this :-)

**Comment by kriegaex** [comment]
Brilliant, that works just fine. Sorry for not checking the settings first. But the issue is still a valid one for your next release, so please keep it open until it is implemented. Thank you so much.

**Comment by AlexandreCassagne** [comment]
@krasa It works just fine, thank you :) is there any roadblock to creating a new release though?

**Comment by krasa** [comment]
yes, time  :-)

**Comment by krasa** [comment]
done
