### ISSUE TITLE
Bug: Latest plugin not rendering default component colors

### ISSUE THREAD

**Issue by mikesaurus** [esteinberg/plantuml4idea#349]
**Actual:**
After upgrading IntelliJ and the PlantUML Integration plugin, diagrams are no longer render with default component colors. Any diagram without colors explicitly declared (`#color`) are rendered in grayscale.

For example, for the following declarations, `User`, `Browser`, `MyService`, and `MyDB` all render in grayscale:
```
Actor User
participant Browser
participant MyService
database MyDB
```
Explicitly adding a color (e.g. `Actor User #yellow`) will render the component with a color.

**Expected:**
In the previous version, components rendered with a default color scheme (light yellow with red lines). Diagrams should continue to render with the same default color scheme for new versions of the plugin.

Previous IntelliJ/PlantUML versions: IntelliJ 2021.2.4 Build #IU-212.5712.43, PlantUML Integration 5.5.1
New IntelliJ/PlantUML versions: Intellij 2022.1 Build #IU-221.5080.210, PlantUML Integration 5.12.0

**Comment by krasa** [comment]
plantuml change:

https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuN9CBialKWWjJYtYAW0APIPd5YJcbIWu5UMNeulvLWQd5fLb9gTofIIM92Ob5gS2XLoSk1nIyrA0HW40

https://plantuml.com/news

**Comment by mikesaurus** [comment]
Closing based on the changes to PlantUML mentioned in the previous comment.
