### ISSUE TITLE
not work with package

### ISSUE THREAD

**Issue by caojianfeng** [esteinberg/plantuml4idea#351]
Not work with package
```
@startuml

class p.c {
}

@enduml
```
![截屏2022-06-28 14 23 00](https://user-images.githubusercontent.com/11853564/176107975-1804396e-5aa0-4daa-a55f-71be100ec312.png)

If I remove the package like this:
```
@startuml

class c {
}

@enduml
```
It will be fine
![截屏2022-06-28 14 23 10](https://user-images.githubusercontent.com/11853564/176108193-c466d39f-435e-41e6-839c-8d530d8940a6.png)

Environment:
Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 2, 2022
Runtime version: 11.0.11+0-b60-7772763 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true, ide.instant.shutdown=false
Non-Bundled Plugins: PlantUML integration (5.13.0), plantuml-parser (0.0.3)

**Comment by krasa** [comment]
Install Graphviz.
