### ISSUE TITLE
Multipage diagram only shows the first page

### ISSUE THREAD

**Issue by jeffryang24** [esteinberg/plantuml4idea#353]
Currently, I use `newpage` keyword inside the plantuml file. This file is rendered using remote plantuml-server (using docker). When trying to copy the SVG source to clipboard, the SVG source is only for the first page.

Past issue: #49 , Don't know why it was resolved, was it probably resolved for local plantuml jar?

Possible idea: https://github.com/plantuml/plantuml-server/issues/7#issuecomment-470509662

### Screenshot

![image](https://user-images.githubusercontent.com/8284757/176910361-29913a5b-1a29-445b-ab43-3bb11ecef36b.png)

**Comment by krasa** [comment]
Yes, that was for local rendering.

You can try it, it calls the server parallelly, not sure if I should limit the number of threads:

[plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/9031772/plantuml4idea.zip)

**Comment by jeffryang24** [comment]
> Yes, that was for local rendering.
> 
> You can try it, it calls the server parallelly:
> 
> [plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/9031772/plantuml4idea.zip)

Sure, I will try it.. :+1:

**Comment by jeffryang24** [comment]
Tested and it is working perfectly. :bow:  :tada: 

![all_pages](https://user-images.githubusercontent.com/8284757/177042413-138410f2-c884-42ba-b47d-19797ab9573c.png)
![single_page](https://user-images.githubusercontent.com/8284757/177042420-c5c0669c-cc7b-4379-abb7-7625edc3971d.png)

**Comment by jeffryang24** [comment]
Thanks @krasa . Since this issue has been resolved in v5.15.2, can I close this issue now? :bow:
