### ISSUE TITLE
Images can't be copied into clibboard

### ISSUE THREAD

**Issue by veselov** [esteinberg/plantuml4idea#357]
Version 5.16.0
IDEA IntelliJ IDEA 2022.1.4 (Ultimate Edition)
Build #IU-221.6008.13, built on July 19, 2022
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.18.10-100.fc35.x86_64
Current Desktop: KDE

Stopped working after latest IDEA update.

Problem:

"Save diagram to clipboard" doesn't work anymore. Attempting to paste just copied image into Gimp says "No image data in clipboard to paste".
I can't find any tools that actually let me see what's in the clipboard buffer.
The workaround is "save diagram", open in another viewer, and then copy that, or use PlantUML URL, but it adds significant delay.
No suspicious messages in IDEA logs.

**Comment by krasa** [comment]
Thanks.  You can update.

**Comment by veselov** [comment]
Awesome, works now, thank you!
