### ISSUE TITLE
Keep getting syntax error

### ISSUE THREAD

**Issue by jmooremcc** [esteinberg/plantuml4idea#358]
I've added @startuml and @enduml in my code but the plugin keeps indicating a syntax error. The code runs with no problem as far as python is concerned and the only errors highlighted by the IDE art the 2 uml tags.

**Comment by krasa** [comment]
what code?

**Comment by jmooremcc** [comment]
I have PyCharm community edition and I want to create UML diagrams from my Python source code.
I successfully did this a few years ago with PlantUML but now it doesn’t work.
I added the @startuml and @enduml tags in my python source code and only get errors.

What am I doing wrong?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by krasa** [comment]
I don't have the code or the error, so how should I know? :-)

**Comment by jmooremcc** [comment]
@startuml
def greet():
    print("Hello World")

@enduml


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by krasa** [comment]
https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKf9JLD8BqfDBT7GjE9I08A2eioy4WqbZzISd7o5yFoYd1GbJIukXzIy591o0000

**Comment by jmooremcc** [comment]
I want to create a UML diagram from my python source code.
I don’t want to create a new file describing the code I’ve already created.
Is it possible to that in PlantUML?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by krasa** [comment]
dunno, this plugin generates images from plantuml code, not plantuml code from python code.

**Comment by jmooremcc** [comment]
Ok, so this tool is not appropriate for my needs.
What you have is equivalent to Microsoft Visio for producing diagrams.
I’m interested in only having a tool that will analyze my Python source code and generate a UML diagram which PlantUML used to do.

**Comment by krasa** [comment]
there is this https://blog.jetbrains.com/idea/2022/03/intellij-idea-2022-1-eap-5/#Export_UML_diagram_to_other_formats
