### ISSUE TITLE
How to solve the problem that the output picture has low pixels and looks blurry?

### ISSUE THREAD

**Issue by tianmingxing** [esteinberg/plantuml4idea#363]
When exporting to an image, it is found that the image has low pixels and looks blurry. In short, the effect of the image is far from that of the real-time preview. How to solve this problem?

**Comment by krasa** [comment]
maybe this? 
![image](https://user-images.githubusercontent.com/1160875/191911392-7e761ede-2f09-4b0a-89b0-156f86c694e4.png)

**Comment by tianmingxing** [comment]
ok，tks！
