### ISSUE TITLE
Changing a participant name's alias on a multiple-page sequence diagram only updates the first page's participant name's alias if using SVG preview

### ISSUE THREAD

**Issue by philCryoport** [esteinberg/plantuml4idea#367]
Hi all, 

There's some issues with participant aliases on a sequence diagram:  If one changes the participant alias, only the first page updates.

Steps to reproduce:
1. Make sure SVG preview is selected in the wrench menu
<img width="291" alt="image" src="https://user-images.githubusercontent.com/28901899/198887911-e8a42f0b-e1bd-40f3-8c22-a28c0fc876ad.png">
2. Starting with the basic Alice / Bob file (I took out the `autonumber` directive to simplify things):

```
@startuml
'https://plantuml.com/sequence-diagram

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
```
<img width="287" alt="image" src="https://user-images.githubusercontent.com/28901899/198887657-a8f7b1a2-8e9f-4b99-8713-53de5afe8aa6.png">

3. Ok let's split that into two pages:
```
@startuml
'https://plantuml.com/sequence-diagram

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
newpage
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
```
<img width="298" alt="image" src="https://user-images.githubusercontent.com/28901899/198887707-3f0875e0-0eab-4bd2-941e-085b869f9dc3.png">

4. So far so good.  Now let's rename Alice to "Alice Waters":
```
@startuml
'https://plantuml.com/sequence-diagram

participant "Alice Waters" as Alice

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
newpage
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
```
<img width="413" alt="image" src="https://user-images.githubusercontent.com/28901899/198887758-4feabc3e-2e42-4e7f-b0b8-2d125b7f87f3.png">

And voila:
* Page 1 shows the expected:
** "Alice Waters", and
** "Bob"
* Wheres page 2 has separate participant blocks for:
** "Alice Waters" (inherited from page 1), 
** "Alice" (because the SVG generator sees page 2 has an "Alice" and doesn't look to see if that's an already-declared `participant`

There is a temporary workaround to make the display work as expected:

1. Select the wrench:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/28901899/198887911-e8a42f0b-e1bd-40f3-8c22-a28c0fc876ad.png">
2. Un-select "SVG Preview"
3. Now see the diagram one expects:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/28901899/198887989-dd2a1bae-99b3-4025-8d38-a3e182772626.png">

**Comment by krasa** [comment]
It is due to an optimization, only a changed page is rendered. 
Perhaps I could add settings to disable it.
Reload button can be used as a workaround.

**Comment by krasa** [comment]
update and set `Cache size` to 0
![image](https://user-images.githubusercontent.com/1160875/199055511-a10cd204-1788-47f3-a8bf-abac848d1210.png)

**Comment by philCryoport** [comment]
Confirmed, with plugin 5.19, setting `Cache size` to 0, creating a participant alias where none was for an existing participant does work!
