### ISSUE TITLE
Pop out diagram preview

### ISSUE THREAD

**Issue by y-luis-rojo** [esteinberg/plantuml4idea#376]
I was not able to find a way to pop out the diagram preview from the editor into a new IDE window. Is that possible? Could it be a feature in next releases? This is particularly useful when using multiple displays where we could work on the code in one and have the preview in another one with a wider overview.
![image](https://user-images.githubusercontent.com/8008773/212966343-48761783-8dd2-4e37-bf3c-bec997604a48.png)

**Comment by krasa** [comment]
it is possible - shift+F4
![image](https://user-images.githubusercontent.com/1160875/212988640-3b990c7e-7379-410f-8d16-92888fa9d8e8.png)

**Comment by y-luis-rojo** [comment]
OK, so 2 IDE windows, one in code mode and the other in preview, didn't see it that way, thanks.
