### ISSUE TITLE
Auto-save all files periodly when PUML diagram is open

### ISSUE THREAD

**Issue by natebowang** [esteinberg/plantuml4idea#377]
PUML is a very helpful tool. And plantuml4idea makes visualisation more efficient. Recently, I draw a diagram and open it aside with the source code to implement it. All works very well except for a little glitch. 

When the PUML diagram is open, all files, like .java .ts, will be auto-saved about every 2 seconds. Save will trigger code formatting according to my configuration. And code formatting will delete extra empty lines. So when I input a new line but haven't input any character, the line will be deleted in 2 seconds, which makes it very difficult to edit. 

Could you please make this plugin only auto-save .puml files? Thanks.

**Comment by krasa** [comment]
Are you using https://plugins.jetbrains.com/plugin/7642-save-actions ?

**Comment by natebowang** [comment]
No. I'm using [this build-in feature](https://www.jetbrains.com/help/idea/saving-and-reverting-changes.html#actions-on-save). Enabled `reformat code` on save.

**Comment by natebowang** [comment]
I found an easy work around: 
1. Right click on the diagram and click `Open in external editor as PNG image`
2. Close the PUML tab in the Intellij editor. 

Then I can have a static diagram aside and auto-save will not be triggerd when editing other source files.

**Comment by krasa** [comment]
You can try it, I will release it tomorrow: [plantuml4idea.zip](https://github.com/esteinberg/plantuml4idea/files/10494449/plantuml4idea.zip)

**Comment by natebowang** [comment]
Thanks, I haven't managed to install it. But I will try.

**Comment by krasa** [comment]
It was released, just update.

**Comment by natebowang** [comment]
Just tried. Perfect. Thanks.
