### ISSUE TITLE
generate associations and Dependencies

### ISSUE THREAD

**Issue by efinder2** [esteinberg/plantuml4idea#380]
Sometimes i Need to generate a class diagram with lots of associations / dependencies. At the moment i create them manually.

It would be nice, if the plugin offered this option. It could read the import statements and parse them.

**Comment by cenqiongyu** [comment]
Yeah. It happens to me too. It can't generate associations and dependencies automatically.

**Comment by krasa** [comment]
IntelliJ itself can generate diagrams from the code, this plugin makes images, not code.
