### ISSUE TITLE
loadJSON not working with latest version

### ISSUE THREAD

**Issue by Damounet** [esteinberg/plantuml4idea#382]
Hello, been using the plug in for ages and decided to download the last version of intellij & of the plug in (I was on a 2021.x version of intellij, don't know which version of the plugin) and it worked like a charm.

But with this new version it seems that the %loadJSON function is not supported anymore ? (https://plantuml.com/fr/preprocessing-json#0e69a97b2cbbc51e)

When I use it, I have this result
![Capture d’écran 2023-02-28 à 16 17 00](https://user-images.githubusercontent.com/7260279/221897153-375fe67b-fd41-41c1-99df-e539e3b2af0c.png)

IntelliJ IDEA 2022.3.2 (Ultimate Edition)
Build #IU-223.8617.56, built on January 26, 2023
Runtime version: 17.0.5+1-b653.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

plugin version 5.22.

I am using a Mac M1 with Mac OS 12.2.1

**Comment by krasa** [comment]
https://github.com/plantuml/plantuml/commit/3af1fb71809f184504b101f6a1baaff8b9689360

**Comment by Damounet** [comment]
ho my!!!

Thank you for pointing that to my attention. Their documentation is not up to date...
