### ISSUE TITLE
PlantUML in javadoc?

### ISSUE THREAD

**Issue by michaelabuckley** [esteinberg/plantuml4idea#383]
Does this plugin support plantuml in javadoc?  I don't see any documentation about the feature set.

I looked at this plugin, but it seems to abandoned - https://github.com/Abnaxos/markdown-doclet
Ideally, it would be compatible with this doclet - https://plantuml.com/doclet

For context, Oracle is thinking about supporting Markdown in Javadoc.  My dream is to embed diagrams in package-info and class javadoc.

**Comment by krasa** [comment]
Support for Doclet would be too much work, imho.
