### ISSUE TITLE
Support for mkdocs_puml

### ISSUE THREAD

**Issue by frague59** [esteinberg/plantuml4idea#384]
Hi, 

Thanks for your great and useful plugin ! 

I'm using [mkdocs_puml](https://github.com/MikhailKravets/mkdocs_puml) for plantuml integration into my mkdocs generated user docs.

This plugin allow to use this syntax:

```
    ```puml
    @startuml
    Alice -> Bob
    @enduml 
    ```
```

I' would be nice to render such declared plantuml diagrams with the plantuml2idea plugin !

Thanks !

**Comment by frague59** [comment]
Yes, of course, but not rendered in the markdown preview:

![Capture d’écran du 2023-03-24 11-52-11](https://user-images.githubusercontent.com/1118696/227502353-0a8e4906-79c1-4db6-a7f4-f5bfc3d0bf98.png)

It should be very nice, thanks !

**Comment by krasa** [comment]
that is a matter of markdown plugin itself

**Comment by frague59** [comment]
OK, thanks !
