### ISSUE TITLE
Compatibility with Android Studio

### ISSUE THREAD

**Issue by IgnacioGarcia198** [esteinberg/plantuml4idea#390]
Hello, I see this plugin is terrific and I would like to use it on Android Studio as well.

**Comment by krasa** [comment]
You can.

**Comment by IgnacioGarcia198** [comment]
How can I use it on Android Studio?

**Comment by IgnacioGarcia198** [comment]
I will try dowloading it and installing the plugin from disk. But not sure why its not available to directly install from Andtoid Studio

**Comment by krasa** [comment]
Which AS version?

![image](https://github.com/esteinberg/plantuml4idea/assets/1160875/3d8d3842-bad5-4749-b159-8083b6b6e644)

**Comment by IgnacioGarcia198** [comment]
Ah mine is the last stable I think, Flamingo. So plugin not ready for this version maybe

**Comment by krasa** [comment]
No, it is compatible.

**Comment by IgnacioGarcia198** [comment]
You are right, somehow I think I was looking at the installed plugins ^^U
Thanks a million!
