### ISSUE TITLE
Preview window does not display AWS icons on version 6.3.1-IJ2023.2

### ISSUE THREAD

**Issue by littlebeeper** [esteinberg/plantuml4idea#400]
The icons from official AWS library are displayed as one big red cross
https://github.com/awslabs/aws-icons-for-plantuml

Please see the attached file
![Screenshot 2023-08-25 at 17 40 17](https://github.com/esteinberg/plantuml4idea/assets/177362/9e326930-90bc-4a78-b73c-6dacc9094157)

**Comment by krasa** [comment]
Disable `SVG Preview` as a workaround.

**Comment by krasa** [comment]
Fixed.

**Comment by littlebeeper** [comment]
Thanks!
