### ISSUE TITLE
remove * + restore not working properly

### ISSUE THREAD

**Issue by alexps99** [esteinberg/plantuml4idea#407]
I m using IntelliJ IDEA 2023.2.2 (Community Edition), 
Build #IC-232.9921.47, built on September 12, 2023, 
Runtime version: 17.0.8+7-b1000.22 amd64
With PlantUML Integration 7.3.0-IJ2023.2

Tried doing this `remove *` with `restore X` with my own files and saw that didnt work. Then tried to use the web example and it seems that it doesnt work as it was supposed to do. In the documentation says this should work and instead i m getting an empty preview: (the small white square)
![imagen](https://github.com/esteinberg/plantuml4idea/assets/48829017/17febec1-bd0b-4c43-b16c-62c807dcfed0)

And as see the problem is with "remove *", because using remove with tags works:
![imagen](https://github.com/esteinberg/plantuml4idea/assets/48829017/8bafe1ab-0cbc-479e-af98-6adf2e7eb300)

Please, repair this so i dont need to mark all my classes/entities/components with a tag

**Comment by krasa** [comment]
Seems like plantuml issue --> https://github.com/plantuml/plantuml/issues

**Comment by alexps99** [comment]
Yes, tested some more outside the pluggin and the the bugs i encountered persisted.  
I should have thought to test outside programs before posting.
Sorry to bother you.
