### ISSUE TITLE
AGPL-3.0 Flagging as banned under NexusIQ scan

### ISSUE THREAD

**Issue by NajibCoutya** [esteinberg/plantuml4idea#418]
The latest net.sourceforge.plantuml : plantuml : 1.2024.3 are flagging a banned AGPL-3.0 license when scanned.
this is preventing the acquisition of the Jars under a secure environment so that the plugin is manually installed under the latest version of IntelliJ.

Any suggestion/solution is greatly appreciated.

**Comment by krasa** [comment]
Easy fix, MIT should be fine, right?
