### ISSUE TITLE
Incompatible with my IDEA

### ISSUE THREAD

**Issue by DreamParadise** [esteinberg/plantuml4idea#421]
IDEA version: `2024.1`
Plugin version: `7.8.1-IJ2023.2`
Screenshot:
![image](https://github.com/esteinberg/plantuml4idea/assets/3191003/cdfd5c6e-114e-4776-b9dd-efeacc457ad0)

**Comment by DreamParadise** [comment]
@krasa If you need more info please let me know.

**Comment by krasa** [comment]
Please update and check the log.

Do you use custom jar? ![obrazek](https://github.com/esteinberg/plantuml4idea/assets/1160875/3dd1d134-242d-46a3-8155-41b706ac903b)

**Comment by DreamParadise** [comment]
Previously I uses bundled jar, and its version is `v1.2024.3`.
Just now I downloaded the latest version `v1.2024.4`, and switch PlantUML to use this custom jar, now the plugin works fine.😃
Below is my current setting.
![image](https://github.com/esteinberg/plantuml4idea/assets/3191003/a1405cb1-fbf0-445d-80b2-8a7227932c3c)
