### ISSUE TITLE
Setting a very high dpi causes the IDE to run out of memory

### ISSUE THREAD

**Issue by cartesian-plane** [esteinberg/plantuml4idea#422]
If the tool window is open while editing the uml.txt file, making a typo like:
```skinparam dpi 3000``` (adding an extra 0) will trigger a warning from intelliJ; something about running out of heap memory.

Could this be fixed by doing some simple validation before rendering is started?

**Comment by krasa** [comment]
No, but you could reduce these values 
![obrazek](https://github.com/esteinberg/plantuml4idea/assets/1160875/799adcd6-aa52-4301-bbc0-d26ffb89512e)

**Comment by krasa** [comment]
Well, it seems that plantuml always returns a huge SVG image, and `SVG preview limit` does not work correctly, it should  limit the rendered image so it would appear zoomed out, now it just reduces the detail, which is quite useless.

**Comment by krasa** [comment]
Thanks, it should now work as expected
