### ISSUE TITLE
Includes not working in Intellij 2024.2

### ISSUE THREAD

**Issue by avall** [esteinberg/plantuml4idea#427]
This sentences like `!include ../style.puml` that they were working fine in "Intellij 2024.1.6",  they are not working in "Intellij 2024.2" and cause the rendering to be empty.

This is a sample:
https://github.com/avall/AWS-SAA-C03/blob/21fe66eeeed5b2ab8a49b2fd3f54cd814a5caddc/assets/uml/000-regions-zones/domain-model.puml#L3

**Comment by krasa** [comment]
Works fine for me. 
Unless  Remote Rendering is turned on...
![obrazek](https://github.com/user-attachments/assets/25ac5cad-c72b-408a-a1fd-7531f0188065)

**Comment by avall** [comment]
> Works fine for me. Unless Remote Rendering is turned on... ![obrazek](https://private-user-images.githubusercontent.com/1160875/357556928-25ac5cad-c72b-408a-a1fd-7531f0188065.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODAwNDAsIm5iZiI6MTcyMzU3OTc0MCwicGF0aCI6Ii8xMTYwODc1LzM1NzU1NjkyOC0yNWFjNWNhZC1jNzJiLTQwOGEtYTFmZC03NTMxZjAxODgwNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMjAwOTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWFlNTU5YzBhYjRiZjllMGE4NWJjNmQwMDM0MzdjMDI5NDI0MzEwOWFlMjFhMDk1ZTViODQ2NjRkMDliMjdjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6t4Pw6wZ11h-xxIRmByM4n3SckX1qae82pxWScLOX-8)

Where do you enable/disable "remote rendering" ?

**Comment by avall** [comment]
Working, thanks a lot ...
