### ISSUE TITLE
Issue when created a default Class diagram

### ISSUE THREAD

**Issue by alexsapran** [esteinberg/plantuml4idea#70]
I created a new class diagram and i got this error. 
The diagram is the one that is automatically generated and i have not yet added or removed any components.
Here what i saw.

![plantuml](https://cloud.githubusercontent.com/assets/2103997/5142059/855ce974-7186-11e4-85e2-b05edf0bddb2.PNG)

**Comment by wowzow** [comment]
Simple fix for this issue on Jetbrains products:  download and install the GraphViz software on your computer, PlantUML needs GraphVis to render 'most' of it's diagrams.

Just FYI.
