### ISSUE TITLE
Do not always refresh the generated image

### ISSUE THREAD

**Issue by bioinfornatics** [esteinberg/plantuml4idea#85]
Dear, sometime the plugin do not refresh the generated image.
To workaround I need to break plantuml syntax as `@startuml` to `@start ` close the project, Open the project and fix the syntax.

**Comment by krasa** [comment]
is there something in the log?

**Comment by bioinfornatics** [comment]
No log are empty.
This problem happend with include. The included file sometime  is not refreshed.

**Comment by krasa** [comment]
Reproduced. Try hitting Save, and then edit the main file. 
PlantUml lib is looking into the physical file, but IntelliJ saves changes only after some actions...

**Comment by krasa** [comment]
fixed
