### ISSUE TITLE
intellij 14 view visibility

### ISSUE THREAD

**Issue by RamonDonnell** [esteinberg/plantuml4idea#86]
In intellij 13 the plantuml view visibility is set by the user, i.e. you open or close it. Typically I would open it ,float it on another monitor and then edit the file.

In 14.0.2 (build 139.659), the plantuml view disappears when editing a non plantuml file, then flickers open/closed when a plantuml file is edited again. This makes it almost unusable.

**Comment by krasa** [comment]
#87 should be enough, but I will pull request a settings for it later.
